### ISSUE TITLE
Uminified version

### ISSUE THREAD

**Issue by michelem09** [720kb/angular-socialshare#10]
Hello,
is it possible to include the unminified version too?
Thanks

**Comment by 45kb** [comment]
@michelem09  Hi, sure it's possible, just change this:

`<script src="dist/angular-socialshare.min.js"></script>`

to this (note src/):

`<script src="src/angular-socialshare.js"></script>`

Let know if you still having troubles, but changing from it should work easily.

**Comment by michelem09** [comment]
Oh well, I didn't see the src dir :)
Thanks!

**Comment by 45kb** [comment]
@michelem09  You're welcome at anytime! :)
