### ISSUE TITLE
social share Url expression

### ISSUE THREAD

**Issue by imperat0r** [720kb/angular-socialshare#101]
When I set socialshare-url="{{someExpression}}" which is I belive important option I some important providers not work for example facebook. (Popu is not opening, it opens few miliseconds than closes automatically) When I hardcode some link than it works.

**Comment by 45kb** [comment]
It works, perhaps you are using a timeout or changing the url dynamically?

**Comment by imperat0r** [comment]
It works, sorry, it is probably because I'm in dvelopment enviroment and facebook doesn't want to open popup if url is localhost.

**Comment by 45kb** [comment]
No problems 👍
