### ISSUE TITLE
E-Mail attribute socialshare-to is not optional

### ISSUE THREAD

**Issue by christianhegedues** [720kb/angular-socialshare#102]
If you don't set the socialshare-to attribute for the email provider, the script use the socialshare-body attribute as e-mail address. It's because the questionmark is bind to the if statement for socialshare-to: https://github.com/720kb/angular-socialshare/blob/master/lib/angular-socialshare.js#L387

Cheers!
Chris

**Comment by 45kb** [comment]
Whoops, my bad, i will fix it and release a new version sorry.

Thanks for reporting.
