### ISSUE TITLE
VK share doesn't support text and image

### ISSUE THREAD

**Issue by edencore** [720kb/angular-socialshare#105]
README.md says that I can use `socialshare-text` and `socialshare-media` options to set text and image for vk's share, but this parameters don't work and [code don't even use them](https://github.com/720kb/angular-socialshare/blob/master/lib/angular-socialshare.js#L653-L659)!

Is it possible to fix? I didn't find anything about it in [their docs](https://new.vk.com/dev/share_details) (didn't find english version of docs either)

**Comment by 45kb** [comment]
Hi, thanks for reporting it, yes we could add also
```
url: 'http://mysite.com',
  title: 'Awesome site',
  description: 'It's the most awesome site ever',
  image: 'http://mysite.com/mypic.jpg',
  noparse: true
```

In the meantime i edit the README

**Comment by edencore** [comment]
I can fix this. The only thing I'm not sure: what `noparse` param does and how could I call it? Just `socialshare-noparse`?
Where did you find this information, btw? 😄

**Comment by 45kb** [comment]
Informations are at the link you gave me, scroll down to sharebutton :)
we just need 
```
socialshare-media -> image
socialshare-text -> title
socialshare-description -> description```

noparse will see in the future.

Thanks for your time!

**Comment by edencore** [comment]
Oh, you're correct. I also have found english version. I'll just left it here:

**url** - Link to the page to be posted.
**title** - Post title. If not set, title from the post page will be used.
**description** - Post description. If not set, description from the post page will be used.
**image** - Link to image of the post. If not set, image from the post page will be used.
**noparse** - If true, VK server will not make an additional request to download missing information from the posted page. If false, request will be sent always.
**no_vk_links** - If the value is 1, there will be no active links to VK in the post window.

**Comment by 45kb** [comment]
Yes, just try opening the vk sharer url and put the parameters you'll see it works :)

Let me know if you have any doubt, then i'll wait for your PR ;)
