### ISSUE TITLE
How to set the customized title and description for Facebook share

### ISSUE THREAD

**Issue by qgliu** [720kb/angular-socialshare#109]
I used socialshare-text and socialshare-description for Facebook share, but the popup windows still get getting the title and description from the pages head/meta-data. Anyone suggestions on solving this? I tried to look for online examples, but can't find one. If you know it, could you share? Thanks!

**Comment by 45kb** [comment]
Hi, are you using `tooltip-type=""` ?

Can you paste the html code here please?

**Comment by qgliu** [comment]
Hi,

Below is the code in Jade style. I tried to add/remove tooltip(bootstrap), it makes no difference.

        ```
button.col-md-12.col-xs-6.m-b-xs.btn.btn-default(type='button' href='#' 
          socialshare socialshare-via='XXXXXX' 
          socialshare-provider='Facebook'
          socialshare-text='{{vm.biz.name}}'
          socialshare-description='description'
          socialshare-url='{{vm.currentUrl}}')
            span.fa.fa-facebook-official
            span.m-l-xs like
```

**Comment by 45kb** [comment]
Look here https://github.com/720kb/angular-socialshare#facebook

In the first table column called "method" there is a different type for each attribute, what you are missing is probably `socialshare-type="feed"` which enable you to use the facebook dialog for sharing.
