### ISSUE TITLE
Thumbnail not showing in linkedin share, if url has hash(#!) fragment

### ISSUE THREAD

**Issue by gaurav113** [720kb/angular-socialshare#115]
I am trying to share blog page on linkedin which has url like https://example.com/#!/blogs/123456. 
Page is shared, but thumbnail preview not showing.
I have also converted hash fragment url to tiny url as http://goo.gl/lgeKVK, still thumbnail not showing.
Please suggest

Thanks

**Comment by 45kb** [comment]
Hi, can you paste your html here please?

I don't think it is a problem with the module, this could depend on linkedin which probably don't allow such urls...

**Comment by gaurav113** [comment]
Here is the HTML code. Please have a look into it and let me know what is the issue exactly.
Thanks
<a socialshare-popup-width="800" socialshare-popup-height="400" socialshare-source="https://goo.gl/qMDd6S" socialshare-description="Check this out!" socialshare-text="Social Content is Stranded" socialshare-url="https://goo.gl/qMDd6S" socialshare-provider="linkedin" socialshare="" class="ln" href=""><i class="fa fa-linkedin"></i></a>

**Comment by 45kb** [comment]
Ok, problem is linkedin related, 

Open this: https://www.linkedin.com/shareArticle?mini=true&url=http://google.com

And then open this: https://www.linkedin.com/shareArticle?mini=true&url=https://www.linkedin.com/shareArticle?mini=true&url=http://goo.gl/lgeKVK

They are probably not allowing such hash in urls.
