### ISSUE TITLE
angular-socialshare.min.js missing

### ISSUE THREAD

**Issue by jguaneri** [720kb/angular-socialshare#118]
I noticed from the prior commit the angular-socialshare.min.js file has been removed.  Is this intentional?  If so, the bower.json needs to be updated to reflect the angular-socialshare.js file that is present since it is still referencing the angular-socialshare.min.js file.

**Comment by 45kb** [comment]
@jguaneri my bad, thanks for the notification, was my mistake only, i will release a new version including the min files, sorry.
