### ISSUE TITLE
Page with multiple share buttons

### ISSUE THREAD

**Issue by mavillar** [720kb/angular-socialshare#127]
Hi,

   I have a page where I display a set of blog posts and each one has its own share button.

   Once click event is triggered, I change the meta-tags:

    <meta property="og:url" content="XXXX"/>
    <meta property="og:title" content="YYYYYYYY"/>
    <meta property="og:image" content="image.png"/>
    <meta property="og:description" content="the description here..."/>

The fact is that facebook always take data before the change, linkdin take the description bad...

What's the best way to accomplish this?

**Comment by 45kb** [comment]
hi what you mean by "Linkedin take the description bad" ?

For facebook if you use meta og you should simply:

`<a socialshare socialshare-url="{{page_url}}"></a>`

But honestly i am not getting your use case, can you please provide some example of code?

Thank you.

**Comment by mavillar** [comment]
In the template dialog I have:

`                <a class="btn btn-medium center-content radius3 bg-white social_btn" socialshare socialshare-provider="linkedin" socialshare-text="{{text}}" socialshare-url="{{url}}" socialshare-description="{{desc}}">
                    <i class="fa fa-linkedin"></i> Linkedin
                </a>
                <a class="btn btn-medium center-content radius3 bg-white social_btn" socialshare socialshare-provider="stumbleupon" socialshare-text="{{text}}" socialshare-url="{{url}}">
                    <i class="fa fa-stumbleupon"></i>  Stumble
                </a>
                <a class="btn btn-medium center-content radius3 bg-white social_btn" socialshare socialshare-provider="digg" socialshare-text="{{text}}" socialshare-url="{{url}}" >
                    <i class="fa fa-digg"></i> Digg
                </a>
                <a class="btn btn-medium center-content radius3 bg-white social_btn" socialshare socialshare-provider="xing" socialshare-text="{{text}}" socialshare-url="{{url}}" >
                    <i class="fa fa-xing"></i> Xing
                </a>
`

and in my controller, I change the **og** metas:

                ```
$('meta#s_url').attr('content', url);
                $('meta#s_img').attr('content', img);
                $('meta#s_title').attr('content', text);
                $('meta#s_desc').attr('content', "The jander clander......");
```

**Comment by 45kb** [comment]
Ok, so please tell me more about what's wrong in linkedin description...

The `<meta og:>` is read by the facebook bot when you share a page so you can change them on the fly, you need to serve them to the facebook bot by backend as a PHP or Ruby html page for example.

If you want to share the url to the blog page with an image attached then a description and a caption and so on ... you need `socialshare-type="dialog"`  for facebook provider, so that you enable all these options https://github.com/720kb/angular-socialshare#facebook (look for the "dialog" method)

Hope is clear now 👍

**Comment by mavillar** [comment]
When the page load, firstly <meta "og:description"> is set by default. Once I click a share button, I change this meta with the description of the post.

The question is that instead of taking the new description, all take the default description.

**Comment by 45kb** [comment]
As i said above, when you pass an url to facebook, facebook comes on your page (a bot) and read your <meta og:> if you change meta og: by javascript facebook is not able to read the new values ....

**Comment by mavillar** [comment]
so, the question is that, how can I manage a page with multiple share buttons (each button has its own url, text, description and image).

**Comment by 45kb** [comment]
Depends if you want to share using element attributes , or if you want to share from a controller for example, there is a service for that https://github.com/720kb/angular-socialshare#service

**Comment by mavillar** [comment]
I have used the second method and I see one problem. It's like Facebook had a cache that always take the same title, description and so on. Twitter for instance shows the link info supplied.

Is there any way to avoiding facebook cache?

**Comment by 45kb** [comment]
@mavillar Probably facebook gets your `<meta og:>` everytime you share that url, however use this tool to debug the url https://developers.facebook.com/tools/debug/
