### ISSUE TITLE
#foo gets rewritten to /#foo

### ISSUE THREAD

**Issue by rizen** [720kb/angular-socialshare#128]
You cannot use &lt;a href="#foo"&gt;Foo&lt;/a&gt; to link to a target within a page, because socialshare rewrites it to &lt;a href="/#foo"&gt;Foo&lt;/a&gt;.

Is there a way to work around this?

**Comment by 45kb** [comment]
Hi, try installing 2.2.2 version, should work now!

Thanks for reporting

**Comment by rizen** [comment]
Works great! Thank you.
