### ISSUE TITLE
undefined is not an object (evaluating 'configurationElement.provider')

### ISSUE THREAD

**Issue by rizen** [720kb/angular-socialshare#129]
Ever since I switched to version 2.2.1 I now get this error in my console.

<img width="507" alt="screen shot 2016-06-27 at 4 39 43 pm" src="https://cloud.githubusercontent.com/assets/170009/16396773/03bf9444-3c86-11e6-90c7-ba681033252f.png">

However, everything seems to be working.

**Comment by 45kb** [comment]
Hi @rizen i am unable to reproduce this error, are you using configurationProvider?

Please share your code, thank you 👍

**Comment by rizen** [comment]
I've got a lot of angular on that page. Let me put together jsFiddle that narrows the scope of the problem.

**Comment by 45kb** [comment]
@rizen thanks

**Comment by rizen** [comment]
jsFiddle was giving me fits this morning, so I just made it into a stand alone HTML file. 

[test.html.zip](https://github.com/720kb/angular-socialshare/files/341719/test.html.zip)

Also, here's the same error message from Chrome's debug (the first one was from Safari's).

<img width="1353" alt="screen shot 2016-06-30 at 10 00 38 am" src="https://cloud.githubusercontent.com/assets/170009/16493029/9e34583c-3ea9-11e6-88e8-03f501024262.png">

**Comment by rizen** [comment]
You'll notice that I have nothing more than angular and social share loaded and it's causing this error.

**Comment by 45kb** [comment]
My bad you should use `socialshare-provider="google"` and not `socialshare-provider="google+"`

Will update README sorry for that.

**Comment by rizen** [comment]
Thank you sir.
