### ISSUE TITLE
Social share issue when using  socialshare-type="feed" in case of facebook

### ISSUE THREAD

**Issue by manishchauhanquovantis** [720kb/angular-socialshare#132]
When i use  

> socialshare-type="feed"

 in case of facebook share it shows a error     

> " Invalid App ID: 0"

**Comment by rbaarsma** [comment]
Does facebook share even work without AppID anymore? Maybe find a solution for facebook similar to https://github.com/djds4rce/angular-socialshare ?

**Comment by toti1212** [comment]
I had the same error yesterday. Definitely you need to set de APP ID  in `'socialshareVia':'your_app_id`. If you dont have an APP ID you need to create an app in [developers.facebook](https://developers.facebook.com/).

**Comment by septembermd** [comment]
or use socialshare-via="app_id" attribute in your template.
Looks like facebook made app ID required recently and you have to create share app on https://developers.facebook.com and use your app id.

**Comment by 45kb** [comment]
Hi, yes the APP ID is required for feed dialog.
