### ISSUE TITLE
How to Share text with image on Twitter?

### ISSUE THREAD

**Issue by manishchauhanquovantis** [720kb/angular-socialshare#136]
Hi,
How to share image on Twitter i already added meta tags and used photo card
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="xyz" />
<meta name="twitter:creator" content="xyz" />

**Comment by 45kb** [comment]
Just share the page url i guess !?

**Comment by manishchauhanquovantis** [comment]
No it doesn't worked.Do you have any working example?

**Comment by 45kb** [comment]
I guess it is as i said, first create meta tags then share url, is written here https://dev.twitter.com/cards/overview

Look, there is a url validator also.

By default, you can't share or attach any media with the sharer url only, you need to setup the twitter card of your url / page.
