### ISSUE TITLE
Facebook share issue

### ISSUE THREAD

**Issue by Triplecorpse** [720kb/angular-socialshare#138]
Hi! I would like to use FB share button. But the shared information is incomplete. This is my code:
```
<div  class="project-header-info-text-share-fb"
              socialshare
              socialshare-provider="facebook"
              socialshare-text="{{project.project.rusName}}"
              socialshare-description="{{project.project.rusShortDescription}}"
              socialshare-url="{{href}}"
              socialshare-media="{{absPicture}}">
            <span class="project-header-info-text-share-text">Share</span>
        </div>
```
Exactly the same code for VK works well. What can be the issue?
![2016-08-11 2](https://cloud.githubusercontent.com/assets/11461770/17602590/fceb9420-6015-11e6-89e9-06afa1ce0aac.png)

**Comment by Triplecorpse** [comment]
This is VK share. Looks fine.
![2016-08-11 3](https://cloud.githubusercontent.com/assets/11461770/17602709/846e36dc-6016-11e6-8fca-73e293042fa4.png)

**Comment by 45kb** [comment]
To share images and more on facebook you have to use socialshare-type="feed" it's documented in the README https://github.com/720kb/angular-socialshare#facebook
