### ISSUE TITLE
Share count

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-socialshare#14]
could be great

**Comment by ishansharma** [comment]
Should this be taken care of in Angular? 

The way I understand, Angular is only for front end. If we are getting number of counts, we are adding extra requests from user's browser to social networks. And IIRC, some of them require API keys and all. 

I don't think this should be done at all.

**Comment by 45kb** [comment]
@ishansharma Well actually this is a really cool feature, but this implies having to support and mix social API SDKs i guess. :+1:

**Comment by 45kb** [comment]
you can now refer to this https://github.com/720kb/angular-socialshare/issues/36

thank you
