### ISSUE TITLE
"Invalid App ID: 0" Message using facebook provider

### ISSUE THREAD

**Issue by etrivinos** [720kb/angular-socialshare#140]
Using social-share-provider="facebook" with social-shared-type="feed" give the following error when we try to shared:

Invalid App ID: 0

![facebook-error](https://cloud.githubusercontent.com/assets/3058683/17705480/24bebd66-639e-11e6-92e0-31ea41b8cac0.png)

**Comment by 45kb** [comment]
Hi @etrivinos look,

First of all, this: `social-share-provider="facebook" with social-shared-type="feed"`

should be: `socialshare-provider="facebook" with socialshare-type="feed"`

Then, you have to set your facebook APP_ID through `socialshare-via="APP_ID_HERE"`

**Comment by etrivinos** [comment]
thanks.

**Comment by Gajananghuge** [comment]
Hi still i am facing same issue. Here is my code 

`<a href="#" socialshare socialshare-provider="facebook" socialshare-type="feed" socialshare-via="1464177653822593" socialshare-media="https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" socialshare-text="This is test" socialshare-description="This is my test data" socialshare-url="www.xyz.com" socialshare-popup-height="300" socialshare-popup-width="400" socialshare-trigger="click" ><i class="fa fa-facebook"></i>Facebook</a></li>`

**Comment by shanthakumarf22** [comment]
+1

**Comment by orfeoetlorchidee** [comment]
Not sure you fixed your problem. I had the same one trying to do the FB.ui but it didn't work...dunno why. At the end i did a custom button from the code that the button configurator gave. Maybe my answer here helps you with what you need.
http://stackoverflow.com/questions/39394371/facebook-social-button-plugin/42932402#42932402
