### ISSUE TITLE
Share on Facebook is not working for text/description

### ISSUE THREAD

**Issue by iseif** [720kb/angular-socialshare#141]
Hey,

  I want to share a text to facebook assigning the text as following:

```
<a socialshare socialshare-provider="facebook" socialshare-type="sharer" socialshare-description="Description Text" socialshare-text="text" href="#">
     <i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i><span style="padding-left: 15px;">Facebook</span>
</a>
```

Give an error page from facebook. If I provide an URL then the URL appears.

Thanks.

**Comment by 45kb** [comment]
Hi you have to use the dialog `socialshare-type="feed"` and provide a valid FB_APP_ID inside `socialshare-via="APP_ID"`

**Comment by dariospadoni** [comment]
I have the same issue and I can't figure out the reason. Here's my markup:

```
<a socialshare="" 
    socialshare-provider="facebook" 
    socialshare-via="370114350029889" 
    socialshare-type="feed" 
    socialshare-description="Unterkunft Casa Vincenzo in Agropoli, Campania buchen" 
    socialshare-media="https://s3.eu-central-1.amazonaws.com/amavido-production-optimized/profile/57a9ebe9f9cc77ed4ba7b6c7/large/44801620-1111-11e6-bdfd-d78f844b0216.jpg"        socialshare-text="Unterkunft Casa Vincenzo in Agropoli, Campania buchen" 
    socialshare-caption="amavido" 
    class="sc-btn sc--facebook">
```

You can have a look [here](https://www.amavido.de/italienische-doerfer/unterkunft-agropoli-kampanien) 

If I share the page by pasting the URL on facebook all the info is retrieved correctly. However if I click the share button on the page itself, I can only see the exact image and caption but text and description are empty....

**Comment by rajathms** [comment]
@dariospadoni  it (facebook- feed dialog) also  requires `socialshare-redirect-uri=""`, just add that attribute it will work fine

**Comment by dariospadoni** [comment]
@rajathms sorry but still not working...

**Comment by rajathms** [comment]
@dariospadoni sorry it should be `socialshare-url=""`

Here is a working [Plunker](https://plnkr.co/edit/0a0H9P?p=preview) with your data, have a look at it.

https://plnkr.co/edit/0a0H9P?p=preview

**Comment by dariospadoni** [comment]
That's it! It works, thank you so much @rajathms

**Comment by ignivahermenpreet** [comment]
Sorry. Text sharing is not working. Can you please provide me any other demo. Because above demo only share static url or image. But text sharing is not working on facebook.
