### ISSUE TITLE
Wrapper to automatically include multiple social services

### ISSUE THREAD

**Issue by chungconscious** [720kb/angular-socialshare#142]
Just discovered this plugin - looks awesome!

**Question:** 
From the looks of it, if I want to provide sharing options on 10 social networks.. and I have 5 templates (e.g. 5 different URL's I want to share), it looks like I need to have 10 x 5 = 50 <a> tags using this directive. 

Is there an option to globally define the social networks I want to enable (just 1x), and then in my 5 templates, include them all via 1 directive? 

This seems easier to implement and maintain? 

Please advise, thanks!

**Comment by 45kb** [comment]
Hi @chungconscious yes, read here : https://github.com/720kb/angular-socialshare#globals

**Comment by chungconscious** [comment]
@45kb - thanks for the pointer. 

I was looking for a directive to standardize the look & feel across multiple pages and to simplify code.

Essentially 1 directive that internally included ALL the shares... So instead of N number of these on every page throughout my app wherever I wanted a share, 

<button socialshare="" ...>
<button socialshare="" ...>
<button socialshare="" ...>
<button socialshare="" ...>
<button socialshare="" ...>
...

I'd just have 1 of these 
<mySocialShare share-url="www.foo.com" ...>

**Comment by 45kb** [comment]
Oh... got it now, no it's not possible with the current imlementation
