### ISSUE TITLE
Email option: always opens in same window - working as designed? 

### ISSUE THREAD

**Issue by chungconscious** [720kb/angular-socialshare#143]
Is there an option to launch the email share in a separate window? 

I've tried target="_blank" in the tag, but that doesn't do anything.

**Comment by 45kb** [comment]
Email sharing is a simple and optionated mailto:// link

read here http://stackoverflow.com/questions/8549816/open-the-href-mailto-link-in-new-tab-window

**Comment by chungconscious** [comment]
Ah right :) 

But for users that have a browser-based default mail client, the UX is that 

1. they click "Share via Email" link on website 
2. they complete their email and hit Send
3. at least for Gmail, they are taken to a page saying their email was sent
4. nothing else happens

The user could close the tab, thinking the website they are visiting was on another tab. They might also sit there waiting a while, thinking the browser will redirect them back to the page they were on before clicking Share.

Is there any way of creating a more consistent experience in line with the other sharing options (e.g. if default client is browser based, open popup... otherwise, open the system mail app)? 

I'm guessing the SO link you sent is the reference, which means No?

**Comment by 45kb** [comment]
mailto:// is a protocol, we can't change that.

To open native apps or mobile apps, you need sort of SDK usually ....
