### ISSUE TITLE
Launch apps instead of browser on mobile

### ISSUE THREAD

**Issue by chungconscious** [720kb/angular-socialshare#144]
Not sure if this is by design, limited by technical feasibility, or if it's a defect... 

On mobile, if a user clicks on Facebook or Twitter share, it would be much more usable if the plugin could:
1) Check if the user has the apps installed
2) If so, launch the app. Else, open default browser

Most users on mobile will have these socials apps installed. If they're forced to manually enter their user name and password in a browser, they will probably abandon the process and not share.

**Comment by 45kb** [comment]
That's a good idea, actually: i don't know if is there any chance to trigger apps without SDK installed, i guess no, but i could mistake.

Any idea?

**Comment by 45kb** [comment]
On facebook this looks possible only by SDK https://developers.facebook.com/docs/sharing/android

**Comment by chungconscious** [comment]
hm, only found this SO, but it seems inconsistent and not reliable

http://stackoverflow.com/questions/13675535/how-to-launch-apps-facebook-twitter-etc-from-mobile-browser-but-fall-back-to-h

**Comment by chungconscious** [comment]
Another good resource about the topic: 
https://www.quora.com/How-can-I-make-a-link-on-a-mobile-website-open-an-app

IMHO most mobile users who 
1) have the FB/Twitter app (which includes nearly everyone) 
2) and are clicking on "Share on FB/Twitter" 
will have the Expectation that the link launches their app, where their credentials are already stored and they are logged in. 

And I think most of them will 
1) click on the 'Back' button and abort the sharing process if they have to enter their email and password into the mobile browser
2) or complete the process, but begrudgingly wondering why they are being forced to enter credentials when they have the app installed

**Comment by 45kb** [comment]
I refer this https://github.com/720kb/angular-socialshare/issues/36
