### ISSUE TITLE
other than demo; example Facebook sharing is not working 

### ISSUE THREAD

**Issue by abubakarmani1** [720kb/angular-socialshare#148]
please guide me, I am newbie and trying to share my http://localhost:3000 Project-post data to facebook... but its returning an error "Sorry, something went wrong."

whereas the same code is perfectly working for twitter...

here is my code:

<md-button socialshare 
socialshare-provider="twitter" 
socialshare-url="{{currentPageURL}}"
socialshare-text="{{project.title}}"
socialshare-hashtags="{{socialshareHashtags}}"
socialshare-via="{{project.user.displayName}}" >
<div><i class="fa fa-twitter-square fa-5x" aria-hidden="true"></i></div>
<div class="md-grid-text" ng-style="{'width': '100%'}">Twitter</div>
</md-button>

<md-button socialshare 
socialshare-provider="facebook" 
socialshare-url="{{currentPageURL}}"
socialshare-text="{{project.title}}"
socialshare-description="{{project.additionalInfo}}"
socialshare-media="{{project.imageURL}}"
socialshare-source="{{currentPageURL}}"
socialshare-redirect-uri="{{currentPageURL}}">
<div><i class="fa fa-facebook-square fa-5x" aria-hidden="true"></i></div>
<div class="md-grid-text" ng-style="{'width': '100%'}">Facebook</div>
</md-button>

**Comment by 45kb** [comment]
Hi, you are missing two things for facebook:

`socialshare-type="feed"`
`socialshare-via="FB_APP_ID_HERE"`
