### ISSUE TITLE
Include the provider name on documentation

### ISSUE THREAD

**Issue by jofftiquez** [720kb/angular-socialshare#149]
I think the provider names should be included in the docu. For example the google plus implementation, I had to read the code just to know that the provider name was `google+` and not `google` nor `google-plus`.

**Comment by 45kb** [comment]
Hi, all the provider names are written in the DOC, probably we forgot to update the google plus one in the code, i am going to change that to `google`

https://github.com/720kb/angular-socialshare#providers

Thank you for reporting it.

**Comment by 45kb** [comment]
You can use this new version now https://github.com/720kb/angular-socialshare/releases/tag/2.2.6

`socialshare-provider="google"`

**Comment by jofftiquez** [comment]
thanks @45kb :)

**Comment by 45kb** [comment]
You're welcome
