### ISSUE TITLE
Sharing images and content on facebook

### ISSUE THREAD

**Issue by andel7** [720kb/angular-socialshare#15]
I am trying to share specific page with some information
with the following button structure
```
<a href="" socialshare socialshare-provider="facebook"  socialshare-media="https://mysite.com /{{angular_image}}" socialshare-text="{{angular_description}}" socialshare-url="https://mysite.com/{{some_uniq_id}}"> Share me </a>
```
but when facebook share dialog pops up I still see some generic info and not the one I provided.
for example image is not the one I provided in  socialshare-media and neither the text.

**Comment by 45kb** [comment]
Hi @andel7 sorry for the stupid question but, have you tried debugging the url you are trying to share with the facebook debugger https://developers.facebook.com/tools/debug/ ?

Does the problem persists then?

thanks for reporting.

**Comment by 45kb** [comment]
@andel7 Sorry i just found the answer, https://github.com/720kb/angular-socialshare/issues/12

The problem is that facebook seems not allowing media and content sharing via sharer url

**Comment by 45kb** [comment]
ACTUALLY
