### ISSUE TITLE
facebook sharer url change

### ISSUE THREAD

**Issue by davidwilder** [720kb/angular-socialshare#150]
I had to change line 441

from
`'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(attrs.socialshareUrl || $window.location.href)
`

to this
`'https://www.facebook.com/sharer.php?u=' + encodeURIComponent(attrs.socialshareUrl || $window.location.href)`

**Comment by 45kb** [comment]
Hi, it looks like they are both working fine:

https://www.facebook.com/sharer/sharer.php?u=http://google.com

https://www.facebook.com/sharer.php?u=http://google.com

What is the real problem?
