### ISSUE TITLE
Facebook: No Permission.

### ISSUE THREAD

**Issue by smarbos** [720kb/angular-socialshare#155]
Hello, I'm having a issue trying to use facebook share

My current version is: 1.4.5

Im getting "You dont have permission" when trying to share with facebook feed.

![image](https://cloud.githubusercontent.com/assets/9627811/18805577/f4fbaf36-81e7-11e6-8c4b-fb0474fcbd60.png)

My code:
```
<a href=""
                socialshare
                socialshare-provider="facebook"
                socialshare-via="235955076772407"
                socialshare-text="{{ animal.nombre }} esta en adopcion!"
                socialshare-description="{{ animal.nombre }} esta en adopcion!"
                socialshare-hashtags="{{ genero }}, {{ animal.nombre }}, adopta, adoptaungalgoenargentina, galgosEnAdopcion, stopGalgueros"
                socialshare-media="{{ apiEndpoint }}/static{{ currentImage }}"
                socialshare-from="adoptaungalgoenargentina"
                socialshare-type="feed"
                socialshare-url="{{ currentDomain }}/perfilAnimal/{{ animal.id }}">
                    <span class="social-button social-button-facebook"><i class="fa fa-size_small fa-facebook" aria-hidden="true"></i></span>
                </a>
```
The API returns:
```
__ar: 1
__sf: "o"
bootloadable: {}
error: 1373034
errorDescription: "No tienes el permiso necesario en la página especificada para realizar la acción solicitada."
errorSummary: "No tienes permiso"
ixData: {}
lid: "6333722417937043191"
payload: null
```

It uses to work, but now it doesnt.

The app is active and available for the users in the developers.facebook panel.

**Comment by 45kb** [comment]
Hi @smarbos that's a problem on facebook not on this module, try to understand what changed in the last days, maybe you don't have permission to post or attach media?!?

Try googling for that error message.

This is not really something you have to fix from the javascript side i am quite sure.

Let me know if i can do something but i am afraid it's really up to facebook.
