### ISSUE TITLE
Share, but open graph meta tags are parsed by Facebook

### ISSUE THREAD

**Issue by pratiksha2211** [720kb/angular-socialshare#156]
Hello 

It was not taking socialshare-description and socialshare-text in facebook share instead of it try to find meta tag in view page. which are dynamic

I have used metaservice in angular to add meta in page so it take {{metaservice.metaTitle}} like text in share

Please help me how it suport in such dynamic page

**Comment by 45kb** [comment]
Hi @pratiksha2211 i am not a guru of facebook api, but it seems to me that facebook bot crawls your meta og tags first of all, so if you want to share something without the bot to crawl them, i am afraid you have to remove the meta tags.

I tried to look at their documentation but it seems to me that there is nothing to do, meta og is made exactly for the facebook bot to get informations about your site.

**Comment by pratiksha2211** [comment]
Okay But my site page is dynamic and require to add all meta tag i can't remove meta tag..
As you told i will try to feed dialog.. may be it works

**Comment by pratiksha2211** [comment]
Hello 

I didnot find how to use feed dialog 

i dont no if i provide link like 

<a href="#"
socialshare
socialshare-provider="faceveook"
socialshare-text="720kb AngularJS Socialshare"
socialshare-hashtags="angularjs, angular-socialshare"
socialshare-url="http://xyz.com">
Share me
</a>

then why they are taking meta from Page ? Can we not provide all meta here?

**Comment by pratiksha2211** [comment]
I have try to use feed dialog like this 

<button class="btn btn-medium font-bold"
                            socialshare
                            socialshare-provider="facebook"
                            socialshare-type="feed"
                            socialshare-via="231850643820058"
                            socialshare-text="test1212"
                            socialshare-caption="test1212"
                            socialshare-url="http://xyz.com"
                            socialshare-redirect-uri="http://xyz.com"
                            socialshare-popup-height="300"
                            socialshare-popup-width="400"
                            socialshare-trigger="click">
                        <i class="fa fa-facebook"></i> Share on Facebook (feed dialog)
                    </button>

But it still {{metaservice.metaTitle}}. 

I have used meta service for dyanamic meta..

Can anyone help me?

**Comment by 45kb** [comment]
I refer it maybe somebody can help on this https://github.com/720kb/angular-socialshare/issues/153
