### ISSUE TITLE
Share on reddit sub-reddit

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-socialshare#16]
Need to investigate if possible

**Comment by ishansharma** [comment]
Some playing with reddit share code and I got this! Will send pull request shortly! :smile:

**Comment by 45kb** [comment]
@ishansharma  Absolutely appreciated! Thank you a lot man :smiley:

**Comment by ishansharma** [comment]
Added in #23 

While I was at it, made minimum popup dimension 900 x 650 since reddit is broken at 500 x 500.

**Comment by 45kb** [comment]
@ishansharma  what about if window dimension is too small, will too large popup cause scrollbars to appear in the browser or it will be resized to fit the window by default?

Need to investigate this .... :)

**Comment by ishansharma** [comment]
Large popup doesn't cause scrollbars to appear.

It's CSS issue on Reddit's site. Everything is fine till ~850px. Below that, either sidebar starts overlapping submission fields (Safari) or sidebar comes about the submission fields in a terrible way. 

Safari:

<img width="596" alt="safari" src="https://cloud.githubusercontent.com/assets/1873271/8634606/9c53835c-281c-11e5-8ff7-181aae4c07e2.png">

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/1873271/8634620/018b6064-281d-11e5-8be4-c872b0b96565.png)

**Comment by 45kb** [comment]
Awesome, yes reddit site unfortunately is not responsive, no problems, thanks for the tip
