### ISSUE TITLE
Does this provide social count

### ISSUE THREAD

**Issue by pratiksha2211** [720kb/angular-socialshare#161]
Hello 

This is very nice plugin used in angular..

But my current requirement is also to show count like sharethis provide..

Currently my sharethis plugin not working in single page angular app so i am using your socialshare plugin

But can you guide me how to get count for specific url from social media

**Comment by 45kb** [comment]
Hi, It doesn't atm, these things you can do by provider SDK or API, this module is not aimed to use them, at least not for the moment. 👍
