### ISSUE TITLE
trying to share .png image on facebook but when it is shared can't see image on my shared article.

### ISSUE THREAD

**Issue by manishchauhanquovantis** [720kb/angular-socialshare#162]

**Comment by 45kb** [comment]
Hi please provide a working example or a jsfiddle. thanks

**Comment by 360disrupt** [comment]
I think I have a similar issue. When using the directive, it just shows plain text. When I paste the page url into facebook it shares the page with the `og:meta`. I add my own `og:meta` tags after loading everything and my site is cached on `prerender.io`.

Site: http://photoshop-battle.com

**Comment by 45kb** [comment]
If you use og: metas facebook crawls them when sharing your urls. There is nothing we can do for this, it's facebook behavior
