### ISSUE TITLE
Is it possible to share image with text and link in twitter, linkedIn, google plus like facebook, printerest? 

### ISSUE THREAD

**Issue by soniasarangal** [720kb/angular-socialshare#164]

**Comment by 45kb** [comment]
Hi @soniasarangal  if it's not documented here (https://github.com/720kb/angular-socialshare#doc) means it's not possible, due to the provider rules/APIs.

**Comment by pam81** [comment]
hi @45kb how it was achieve on the linkedin share in the demo? http://720kb.github.io/angular-socialshare/

I can't add an image to show in linkedin like in the demo

**Comment by jrogatis** [comment]
https://developer.linkedin.com/docs/share-on-linkedin
this is the link for share api at Linkedin... so its possible....

**Comment by 45kb** [comment]
Hi, we don't use APIs or SDKs Linkedin has no sharer image option unfortunately https://developer.linkedin.com/docs/share-on-linkedin#!

**Comment by 45kb** [comment]
@pam81 the image is crawled by linked in i guess they take all the images urls in your page and then you choose which to add from the sharing popup, they have no image param for sharer url

**Comment by jrogatis** [comment]
a possible solution is `embed` this meta tags to page... 
html prefix="og: http://ogp.me/ns#">
<head>
  <meta property="og:title" content="My Shared Article Title" />
  <meta property="og:description" content="Description of shared article" />
  <meta property="og:url" content="http://example.com/my_article.html" />
  <meta property="og:image" content="http://example.com/foo.jpg" />
</head>
<body>
   …
</body>
</html>

**Comment by 45kb** [comment]
Yes, maybe with og:image you'll get it to crawl it as first image in the page and indeed the demo works like that if you see 👍

**Comment by pam81** [comment]
Hi thanks @45kb and @jrogatis I add the og:image on my site and now it's working. 
Now I find another issue : it's not working when I try to "send to individuals" only. I have no error, I'm getting linkedin message "Great! You have successfully shared this update" but when I see on my chats the shared link is not there.
