### ISSUE TITLE
cant update the socialshareText attr on whatsapp

### ISSUE THREAD

**Issue by YanivPlaybuzz** [720kb/angular-socialshare#166]
i have a whatsapp button generated with socialshareText = 1 , than i apply a change to socialshareText to be 2 but the when i press on the whatsapp icon it shares socialshareText=1 instead of 2 . but the filed is updted correct on sms and facebook .

**Comment by YanivPlaybuzz** [comment]
i guess its because the following code : 
      //**** whatsapp can't share without an element clicked (href)
      //this.whatsappShare = manageWhatsappShare;

**Comment by 45kb** [comment]
Hi can you create a fiddle with your code please, that part of the code should not be the  problem.

Thanks
