### ISSUE TITLE
Change the documentation for the Google Plus sharing

### ISSUE THREAD

**Issue by Maskime** [720kb/angular-socialshare#167]
Hi,

It took me some time to figure the provider to use for the Google+ sharing.
It'd be nice to fix the `README.md` file to put the actual value `google+` just for easing the use.

Nice job anyway, thanks for your work.

**Comment by 45kb** [comment]
Hi @Maskime it's just `google` not `google+`

I'll make it more clear but how is it working for you using `google+` it's a mistery actually...!?

**Comment by Maskime** [comment]
I'm using an old version... My bad... thanks

**Comment by 45kb** [comment]
you're welcome, no problem 👍
