### ISSUE TITLE
On my Agular JS app when i click share button it also logouts the user! 

### ISSUE THREAD

**Issue by Axheladini** [720kb/angular-socialshare#170]
On my Agular JS app when i click share button it also logs me out from the app!

**Comment by 45kb** [comment]
Hi, can you be more clear, because socialshare has nothing to do with logs and the lib does not touch any log information or api

thanks

**Comment by Axheladini** [comment]
Actually it was some other javascript issue conflicting. Its fixed now!. Thanks for your replay!

**Comment by 45kb** [comment]
great, glad that it working now! you're welcome
