### ISSUE TITLE
FB messenger share link not working

### ISSUE THREAD

**Issue by Ketan-saresa** [720kb/angular-socialshare#172]
FB-messenger share url not allowing any path params, this what i m doing 

```< a href="" socialshare socialshare-provider="facebook-messenger" socialshare-url="https://siteName.com/home?shareSong='song name'&artist='artist name' " ng-click="closeShareDialog()">```

by inspect element when i am seeing the value of href is comes perfect but while clicking on it from mobile it opens the messenger but only "https://siteName.com/home" comes my path params doesn't come.

Is there any solution for it ?? its happening only in facebook messenger  rest all whatsapp, sms, mail, facebook post working perfectly.

Please help as soon as possible

**Comment by 45kb** [comment]
Hi, try ```socialshare-url="{{encodeUriComponent(https://siteName.com/home?shareSong='song name'&artist='artist name' ) }}"``` your query string is not url encoded

**Comment by Ketan-saresa** [comment]
Nope, tried it it's still not working, same issue coming, and in the directive it encodes the url before assigning it to the href so there is not such need to encode it in html.

**Comment by Ketan-saresa** [comment]
Hello, when i try this on my localhost with my local IP it works perfect but when i deploy in on server then it doesnt allows the path params. Is there any solution to this ??

**Comment by Ketan-saresa** [comment]
Finally got the root of the issue. in facebook messenger u have to prefix some text before link. like 
href = "check this song" + "https://siteName.com/home?shareSong=song name&artist=some artist"
