### ISSUE TITLE
Option to specify delimiter/spacer rather than hard-coded?

### ISSUE THREAD

**Issue by alexstanbury** [720kb/angular-socialshare#175]
When sending SMS, there is a hard coded hyphen before the URL in the message, would it not be more flexible to specify this oneself rather than be forced to use it?

**Comment by 45kb** [comment]
@alexstanbury hi, can you point me to the line number please, i am missing this... thanks

**Comment by alexstanbury** [comment]
@45kb sure, line number 833

`var body = encodeURIComponent(attrs.socialshareText.replace('%','')) + ' - ' + encodeURIComponent(attrs.socialshareUrl)
`

**Comment by 45kb** [comment]
Ops, you're right, that shouldn't be there i guess. have you tried the sms share removing that hypen?

**Comment by alexstanbury** [comment]
@45kb i'm not about to do that without amending the source code, which is something i'd like to avoid because I want to load from CDNJS in production. 

Also, whatsapp share has a space added between socialshareText and socialshareUrl:

(line 821) `var href = 'whatsapp://send?text=' + encodeURIComponent(attrs.socialshareText + ' ') + encodeURIComponent(attrs.socialshareUrl || $window.location.href);
 `
It's not a show stopper, but I think it could be a lot more flexible if a user was able to specify their own delimiter, with a default fall back if none is passed.

**Comment by 45kb** [comment]
@alexstanbury yes i agree, i don't remember if that's a mandatory hypen or not, i don't think so i will try to investigate this, if you then want to make a PR for this and contribute i'll be much glad for it. otherwise don't worry 👍  thanks for spotting this out.

**Comment by alexstanbury** [comment]
@45kb I think probably the easiest and most flexible way to do it would be to remove any hard coded delimiters from the plugin code, then users can just add whatever they like to the end of the socialshareText string. I've not done a PR before but will see what I can do tomorrow. Thanks for being so quick to respond and for such a useful plugin!

**Comment by 45kb** [comment]
@alexstanbury you're welcome and yes i agree, should be just to remove them and let user decide indeed.

If you need help on making PR just ping me i'll be glad to help. Literally all you have to do is to FORK this repository , make the changes to the interested file and just click "PULL REQUEST"

**Comment by 45kb** [comment]
@alexstanbury thanks for your help! you can now update your module version to `2.3.4`

closing :)

**Comment by alexstanbury** [comment]
Hi, I noticed CDNJS has not picked up version 2.3.4 yet, it's still stuck on 2.3.3. Is there anything you can do to get it updated?

**Comment by 45kb** [comment]
@alexstanbury Hi, actually i . really think the only option is to wait or open them an issue, they do all automatically afaik.

**Comment by alexstanbury** [comment]
Ok, I'll see what I can do, thanks.

**Comment by 45kb** [comment]
@alexstanbury thanks! i believe they have many open PR so maybe it's just to wait but actually i don't know
