### ISSUE TITLE
can we change socialshare-url image size

### ISSUE THREAD

**Issue by herocorum** [720kb/angular-socialshare#176]
I have an jpg url in socialshare-url and I added  .... jpg&w=800&h=600 but it doesn't  able to detect like href did .Do we have chance change social sharing images (not the frames of socialshare-popup-height)

**Comment by 45kb** [comment]
@herocorum when sharing images the image has to be a fixed width and height according to the social-platform specs, i'd use only 250x250px images for sharing on facebook (just an example).

Go through the social-platform API doc and see what is the format and the sizes of the image to share ;)
