### ISSUE TITLE
FbShare Issue

### ISSUE THREAD

**Issue by AhmedHassan07** [720kb/angular-socialshare#178]
On socialshare-provider="facebook"
socialshare-media , socialshare-title, socialshare-description not working on 
socialshare-type="share"

**Comment by mebibou** [comment]
ah yes the api as changed, seems only `link`, `hashtag`, `quote` and `mobile_iframe` are available now on the API, wonder when they changed that

**Comment by 45kb** [comment]
@mebibou yes unfortunately you're right https://developers.facebook.com/docs/sharing/reference/share-dialog :(

**Comment by 45kb** [comment]
PR here would be much appreciated guys 🥇

**Comment by rajathms** [comment]
@AhmedHassan07  Could you please explain what exactly the error is, so that it will help me to figure out.

As i tested in my local, it's working good , if you get me the error message that would be great.
Thank you,

**Comment by 45kb** [comment]
@rajathms Hey thanks, look here https://developers.facebook.com/docs/sharing/reference/share-dialog actually the params are changed  , it's to change the attributes according to it

**Comment by rajathms** [comment]
@mebibou  @45kb  
Api /params are not changed, they support title, description etc... which ever we have mentioned in the [readme](https://github.com/720kb/angular-socialshare#facebook) 

i think you can test by adding title,description and picture(media) in their [example](http://www.fbrell.com/saved/809b6c409f3c8dd307023cd78cdb6111) (facebook's try it yourself example) itself

**Comment by 45kb** [comment]
@rajathms but it looks to me that some attribute is no more valid and some is missing... :D

**Comment by rajathms** [comment]
@AhmedHassan07 @45kb  here is the working example [Plunker](https://plnkr.co/edit/mvCeoy?p=preview) .

you can check this out and you can edit every other filed(attribute) which is there in the our [Readme](https://github.com/720kb/angular-socialshare#facebook).

thank you

**Comment by 45kb** [comment]
@rajathms cool!! could you update the README.md according to this? it's just to remove or add the correct attributes to use for fb `share`

Thanks

**Comment by rajathms** [comment]
@45kb 
Everything is updated, No PR is required for this issue .
Which ever is mentioned in the Readme is working good and fine no PR is required.

thank you

**Comment by rajathms** [comment]
@45kb  Yep! one thing we need to update, 
For now facebook supports only one hashtag through it's API .
We need to mention that in the README.

**Comment by 45kb** [comment]
@rajathms mobile_iframe attribute  is missing nope?

**Comment by rajathms** [comment]
@45kb  yep 
let me update and give PR

**Comment by 45kb** [comment]
https://github.com/720kb/angular-socialshare/pull/192 

can we close this? @rajathms

**Comment by rajathms** [comment]
yes :+1: @45kb

**Comment by 45kb** [comment]
ok @rajathms awesome!
