### ISSUE TITLE
angular is not defined

### ISSUE THREAD

**Issue by StevenSerrien** [720kb/angular-socialshare#179]
Hello!

I'm installing angular-socialshare via NPM and can require the module into my app.
However, when putting the .js file in my source folder and referring to it from my index.html page, it gives me following error.

```angular is not defined at angular-socialshare.js:1109```

Anyone that knows why?

**Comment by 45kb** [comment]
@StevenSerrien did you include the angular.js in your project? (stupid question i know)

**Comment by 45kb** [comment]
closing for long time no feedback.

**Comment by SabiRoth** [comment]
I've got the same problem.. 
I included <script src="vendors/angular-socialshare/dist/angular-socialshare.js"></script> in my html-code. And in my js-code added /*global angular*/ in the beginning. Is it wrong?
