### ISSUE TITLE
Twitter media upload

### ISSUE THREAD

**Issue by nachogarrone** [720kb/angular-socialshare#182]
**Goal**: implement twitter media upload api. 

(`https://dev.twitter.com/rest/reference/post/media/upload`)

**Comment by 45kb** [comment]
@nachogarrone hey this is cool, didn't know twitter introduced this, i will try something for it as soon as i have some time 👍 

If you want you can make a PR and contribute, would be much appreciated!

**Comment by 45kb** [comment]
Reading in the documentation and looks like to me that this requires oAuth so we can't introduce it in the lib. 

Maybe i am mistaking... if so please reply me, thanks.

**Comment by nachogarrone** [comment]
@45kb reading a bit of the 720kb library, it seems that you use Web Intents, that's just open a window with some params. 
You are correct, we should implement the REST API and it requires oAuth.
ref: `https://dev.twitter.com/rest/reference/post/media/upload`

**Comment by 45kb** [comment]
@nachogarrone Yes, the aim is to use everything is possible to use without having to integrate SDKs or oAuth :)

Unfortunately no luck, let's hope Twitter will add some url param for when sharing to attach medias too.
