### ISSUE TITLE
issue while populating data 

### ISSUE THREAD

**Issue by sshekhawat** [720kb/angular-socialshare#184]
Hello 

We are using your js but I am facing some issue, when i pass static data in  whatsapp share its working fine. but when i use data from server api. then didn't get value socialshare-text="{{CoupleName}}"

i checked js (angular-socialshare.js) file and console  then  it shows empty value and when i pass static then it shows value correctly. 
Thanks

**Comment by 45kb** [comment]
@sshekhawat hi, please create a live example jsfiddle or plnkr so that we can help. thanks

**Comment by sshekhawat** [comment]
Thanks for replay 
when i have used updated js file then workin fine.

**Comment by 45kb** [comment]
@sshekhawat cool, you're welcome don't worry!
