### ISSUE TITLE
Can we share image in whatsapp

### ISSUE THREAD

**Issue by sshekhawat** [720kb/angular-socialshare#185]
Hello 
can i share image, title, description and url in whatsapp 
http://www.easeparenting.com/moms/know-the-impact-of-disney-princesses-on-your-child 
see this site example,

**Comment by 45kb** [comment]
@sshekhawat Hi, no it's not possible unfortunately seems that whatsapp has no options for that.

**Comment by nitin-healthians** [comment]
Hi,
I want to share image on whatsapp

**Comment by Vivekpawar760** [comment]
hggh
