### ISSUE TITLE
Support for ResearchGate message

### ISSUE THREAD

**Issue by volfgox** [720kb/angular-socialshare#186]
This module can add support for share via ResearchGate messages.

**Comment by 45kb** [comment]
@volfgox hi, i don't know much about researchgate i discovered it now and it seems it's very popular http://www.alexa.com/siteinfo/researchgate.net

I have no time to check it out, is it a social platform ?

**Comment by volfgox** [comment]
Hi. Researchgate is a academic social network, which academic professors, students and other people share their publications, projects and ... there. It is used in many various ways like [(about)](https://www.researchgate.net/about)
Share your publications, access millions more, and publish your data.
Connect and collaborate with colleagues, peers, co-authors, and specialists in your field.
Get stats and find out who's been reading and citing your work.
Ask questions, get answers, and find solutions to research problems.
Find the right job using our research-focused job board.

**Comment by 45kb** [comment]
@volfgox thanks for clarifications, you know there are plenty of social platforms on the internet and we cannot include them all, so we must choose the most common ones we'll however take this into consideration for later.

**Comment by 45kb** [comment]
merging issue here https://github.com/720kb/angular-socialshare/issues/77
