### ISSUE TITLE
SMS Share URL parameter

### ISSUE THREAD

**Issue by overovermind** [720kb/angular-socialshare#188]
I noticed a small error in the readme:
The url parameter is missing for SMS share:
socialshare-url=""	URL	page URL	Set the url to share

Also, if you do not specify the url, you get "undefined" in your sms text.

**Comment by 45kb** [comment]
@overovermind Hi, thanks... didn't noticed that at all sorry for the inconvenience.

A PR would be appreciated 👍

**Comment by overovermind** [comment]
ok 👍  #189

**Comment by 45kb** [comment]
thanks @overovermind  https://github.com/720kb/angular-socialshare/pull/189

**Comment by 45kb** [comment]
@overovermind v2.3.5 shipped with your fix 📦
