### ISSUE TITLE
Multiple Hastags in Facebook share-type

### ISSUE THREAD

**Issue by vvmsoft** [720kb/angular-socialshare#191]
is there any way to add multiple hashtags for facebook ?

**Comment by 45kb** [comment]
maybe you can try adding hashtags to the text content you want to share.

through the socialshare-hashtags="" it is not possible due to the facebook implementation 

they says:

> A hashtag specified by the developer to be added to the shared content. People will still have the opportunity to remove this hashtag in the dialog. The hashtag should include the hash symbol, e.g. #facebook 


https://developers.facebook.com/docs/sharing/reference/share-dialog
