### ISSUE TITLE
Callback after Twitter share?

### ISSUE THREAD

**Issue by infinacy** [720kb/angular-socialshare#193]
Hi,
Is it possible to have a callback after successful share on Twitter?
Thanks

**Comment by 45kb** [comment]
Hi @infinacy next time please search through the issues before to post a new one :)

https://github.com/720kb/angular-socialshare/issues?utf8=%E2%9C%93&q=callback

Not possible, you have to use the Twitter SDK if you want the callbacks.

**Comment by infinacy** [comment]
Thanks. Sorry I searched through the issues using "Twitter in:title". But it was not found by that way :(

**Comment by 45kb** [comment]
@infinacy no problems at all, don't worry ;)
