### ISSUE TITLE
Help - How to share Canvas to Image with Facebook ? My code won't work

### ISSUE THREAD

**Issue by alphakanal** [720kb/angular-socialshare#194]
Hi!
I'd love to share an image created from a canvas inside my website. But i don't know what is the right way to get this solved. I got a function which creates a image from the blob.
My Code so far: 
```

    vm.createIMG = function () {
      var shareImg = new Image();
      vm.canvas[0].toBlob(function (blob) {
        shareImg.url = URL.createObjectURL(blob);
        shareImg.onload = function () {
          URL.revokeObjectURL(shareImg.url);
        };
        shareImg.src = shareImg.url;
        shareImg.width = 300;
        // from here on i don't know what to do to share this image with facebook
      });

    }; 
```

Does anyone know how to solve this? Appreciate every hint!

**Comment by 45kb** [comment]
@alphakanal try http://stackoverflow.com/questions/18650168/convert-blob-to-base64

Maybe base64 should work.

**Comment by alphakanal** [comment]
Hi!
Thank you for the answer and sorry for my late response - but we've been on holiday :) I'll try this right the next days!

**Comment by alphakanal** [comment]
@45kb I've tried today and yesterday to get this running, but i can't get it running. Maybe it's a simple thing but i'm an beginner and got stuck :-( Maybe you could know how to do it? 
The Sharebutton is in a Directive/Component which is implemeted with a binding to the canvas element in the main page:
`
// Implementation in MainPage:
<social-share-component canvas="vm.canvas"></social-share-component>

// Component HTML:
<a href="" class="btn btn-social btn-facebook" socialshare socialshare-provider="facebook" popup-height="500" popup-width="500" socialshare-media="{{ vm.socialImage }}" ng-click="vm.createImage()" socialshare-url="http://www.my-domain.com"><span class="facebook"></span>Share!</a>
`
The Social Share Controller:
`
function socialShareController(dataService) {

    var vm = this;

vm.createImage = function () {
...
    var canvas = vm.canvas[0]; // Error -> vm.canvas is undefined 
...
}

    vm.$onInit = function () {

      var encodeBlobToBase64 = function () {
        var canvas = vm.canvas[0]; // no error
        var b64Text = canvas.toDataURL();
        b64Text = b64Text.replace('data&colon;image/png;base64,', '');
        var base64Data = b64Text;
        console.log(base64Data);
        return base64Data;

      };
      vm.socialImage = encodeBlobToBase64();
    };

  }
`
The encodeBlobToBase64 function which is called $onInit creates a blank image because the canvas is empty at this stage.
The createImage() which i call with ng-click creates an error, because the binding is undefined...
I'm absolutley lost...

**Comment by 45kb** [comment]
@alphakanal 
Closing issue as it's not related to socialshare module.

We still continue help you if you need, just send a jsfiddle or plnkr, thanks!
