### ISSUE TITLE
Doesn't work on iphone app?

### ISSUE THREAD

**Issue by vaidyaanand** [720kb/angular-socialshare#196]
I have used this plugin in meteor and tested on web. It is working on web fine. But, when I deploy the meteor application on ISO testflight It is not working. I am not able to detect  what is the problem...

**Comment by 45kb** [comment]
@vaidyaanand You should be able to debug your application, please attach more details   so we can help further.

**Comment by vaidyaanand** [comment]
I am able opened a popup on iphone.... but there is no way to go back... How can I get the response ?
'<a class="fbalignfix"flex="100" href="#" socialshare socialshare-provider="facebook" socialshare-trigger="touchstart" socialshare-text="'+$scope.prodDetail[0].description+'"  socialshare-caption="My_Project_Name"  socialshare-type="feed" socialshare-via="1234XXXXXXXXXXX" socialshare-url="https://dummyUrl/'+$scope.proId+'" socialshare-media="https://DummyUrl/'+$scope.proId+'/img1"><img class="fbimgfix" src="share/facebook.png" height="48" width="48">{{"Facebook" | translate}}</a>'+

**Comment by 45kb** [comment]
@vaidyaanand what you mean by go back? 

If you need callbacks after the content is shared you  have to use SDKs this module does not include SDK

**Comment by vaidyaanand** [comment]
Can you give me any idea that how can I do this ? I am struct in this problem from yesterday.

**Comment by 45kb** [comment]
@vaidyaanand  sorry to say but you should read their documentation i can't help much https://developers.facebook.com/docs/sharing

This module is for straightforward sharing you don't have callbacks available without the provider SDK

**Comment by vaidyaanand** [comment]
@45kb Let's say there is a scenario in which user accidentally clicked on the share and they don't want to share anymore and would want to go back. There is no such option in the plugin to go back to the app.

**Comment by 45kb** [comment]
@vaidyaanand that is up to `window.open()` usually you can close the share window, share a screenshot if you can.

**Comment by vaidyaanand** [comment]
When I click on the share Button:-
![img1](https://cloud.githubusercontent.com/assets/22315535/24095765/938af4ea-0d84-11e7-9801-ea6eebacc554.jpg)
when I click cancel or share ...it shows blank window on iPhone:-
![img2](https://cloud.githubusercontent.com/assets/22315535/24095918/457d0a26-0d85-11e7-9f5b-7a6a0a828278.jpg)

**Comment by 45kb** [comment]
@vaidyaanand looks like you are not sharing otherwise facebook was closing the popup itself i believe. Does the content gets shared ?

**Comment by vaidyaanand** [comment]
Yes I have checked the contents got shared... I am not able to detect whats the problem ... everything is working fine except closing the current opened screen. Have you checked it in iPhone from your side ? is it working fine ?

**Comment by vaidyaanand** [comment]
I am passing this param:-
`<a class="fbalignfix"flex="100" href="#" socialshare socialshare-provider="facebook" socialshare-trigger="touchstart" socialshare-text="'+$scope.prodDetail[0].description+'" socialshare-caption="My_Project_Name" socialshare-type="feed" socialshare-via="1234XXXXXXXXXXX" socialshare-url="https://dummyUrl/'+$scope.proId+'" socialshare-media="https://DummyUrl/'+$scope.proId+'/img1"><img class="fbimgfix" src="share/facebook.png" height="48" width="48">{{"Facebook" | translate}}</a>`

**Comment by 45kb** [comment]
@vaidyaanand if the content is shared on facebook this is clearly some problem with facebook you have.

Can you paste the entire url of the blank share window? (the one at the bottom side of the blank window.

**Comment by vaidyaanand** [comment]
we have call fb sharer via attribute. do we have any function to check callback or response ?

**Comment by 45kb** [comment]
@vaidyaanand none as i said if you want to use callbacks you must use the facebook SDK.
