### ISSUE TITLE
Meteor Ios-error

### ISSUE THREAD

**Issue by Pramodaexonic** [720kb/angular-socialshare#198]
After successful completion of sharing Facebook feed, my inappbrowser is not closing, its showing a blank screen.

I have also tried socialsharing redirect-uri, it is only redirecting to a location in inappbrowser.

I just have to go to the app after completion of sharing, for ios.

**Comment by 45kb** [comment]
Better refer to this https://github.com/720kb/angular-socialshare/issues/196

Have you tried mobileiframe="true" perhaps?

**Comment by Pramodaexonic** [comment]
socialshare-mobileiframe="true" is also not closing,  the inappbrowser, is there any other method please tell to close the inapp

**Comment by 45kb** [comment]
@Pramodaexonic looks more like a facebook problem, the popup is . handled by them not by the library, for further help could be great if you share the entire URL you see on the blank page.

**Comment by Pramodaexonic** [comment]
www.facebook.com/dialog/return/close? this URL is on the blank page instead of closing the popup

**Comment by Pramodaexonic** [comment]
Even i have used socialshare-redirect-uri to redirect to to close page with close button on the page in inapp browser when redirected.

called a function window.close() for ios to close the popup its still not working, but on browser its working

**Comment by 45kb** [comment]
@Pramodaexonic  use this https://pastebin.com/raw/hCbsvsMi i added a `console.log` and you should be able to see "I AM SHARING WITH THIS URL:" in your devtools console.

If yes please paste here the entire url.

**Comment by Pramodaexonic** [comment]
We have tried using using the library: got the url in console please check-

https://www.facebook.com/dialog/feed?&app_id=563808870469385&redirect_uri=https%3A%2F%2Fmarket-spider.herokuapp.com%2Fcloseit&link=https%3A%2F%2Fmarket-spider.herokuapp.com&name=Need%20car%20parts&caption=Market%20Spider&picture=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fmarket-spider-bucket%2FbuyProduct%2FxizCSvtDPGw4fzDML%2Fimg1

**Comment by 45kb** [comment]
@Pramodaexonic try look at the facebook documentation if some missing param in your url, i can't help much, also check if your redirect_url does not crash.

I believe in your redirect_uri you should do something like `window.close();` ...

**Comment by Pramodaexonic** [comment]
yes i am trying using window.close() when after sharing the feed we are redirecting the popup to another page with with close button, but winodws.close() seens not working for ios.

so is there any solution to close the popup.

**Comment by 45kb** [comment]
No solutions it's up to your redirect url to close it and neither facebook or angular-socialshare can access it :)

And indeed on iOS seems window.close is not working https://www.google.com/search?q=ios%20window%20close&*&rct=j

You probably need some polyfill for this .
