### ISSUE TITLE
Sharing images on facebook timeline from angular js application

### ISSUE THREAD

**Issue by Moses-Bassey** [720kb/angular-socialshare#199]
Hi,

Please am trying to share an image from angularjs application, the share dialog from facebook seems to pool the image from metadata og:image tag, please can anyone help me out?

**Comment by mikeipic** [comment]
https://external-mia1-1.xx.fbcdn.net/safe_image.php?d=AQD3QsF8QeqM3ate&w=526&h=275&url=https%3A%2F%2Fstatic.ipictheaters.com%2Frw%2Fimagedb%2F15015%2F2052%2F11419_ipic_holidaygiftcard_2015_webbanner_600x379.jpg&cfs=1&upscale=1&_nc_hash=AQC9Aw3k8o6R6Xr8

My application is using an image that I can find where it imported it from,  or whether it is an image from the site.  My otag is a totally different image.

**Comment by rajathms** [comment]
@Moses-Bassey , 
I guess you missed this attribute `socialshare-media=""`   if you add a image link to this attribute it will use the image you added otherwise it will try to fetch from meta data .

Have a look at this [live plunk](https://plnkr.co/edit/mvCeoy?p=preview) , try changing the image link and 
*if you remove the whole attribute, it will use the image from meta data (you check that also)

**Comment by rajathms** [comment]
@mikeipic can share the code, that you are using for sharing on facebook

**Comment by mikeipic** [comment]
Can you explain why this doesn't work if it is that simple?
`  <div class="btn btn-facebook"
                                         socialshare socialshare-provider="facebook"
                                         socialshare-url="https://www.ipictheaters.com/#/streetteam/16/location/Dobbs_Ferry"
                                         socialshare-media="https://static.ipictheaters.com/2011102503/cache/Content/images/marketing/herocrop.jpg">Share</div>`

**Comment by rajathms** [comment]
@mikeipic you missed adding this `socialshare-type="share"`  you need to specify one of them (feed/send/share) as facebook needs to know where you exactly wants to post  for more details please check the links in our Readme

@45kb  I think it is time to update our readme.md mentioning which are are the mandatory fields to be included.

**Comment by mikeipic** [comment]
Thanks a lot.  I appreciate it.

**Comment by rajathms** [comment]
@mikeipic you are welcome.

Can you close the issue, the one you created after this #200 (if it is relating to the same).

**Comment by 45kb** [comment]
@rajathms yes could be great, can you add those changes to the README in a PR?

**Comment by rajathms** [comment]
@45kb yea sure

**Comment by vamsi0391** [comment]
Hi, 
I'm using this plugin my code is as follows:
`<p socialshare
                  socialshare-provider="facebook"
                  socialshare-type="share"
                  socialshare-via="109096989719772"
                  socialshare-media="{{share.goalimg}}"   
                  socialshare-title="vm.goal.goalText"      
                  socialshare-mobileiframe = "true"                  
                  socialshare-url="{{share.goalURL}}"        
                  socialshare-popup-height="300"
                  socialshare-popup-width="400"
                  socialshare-trigger="click">FACEBOOK </p>`

- socialshare-media="{{share.goalimg}}"   //Dynamic img url (not woking if I keep static url also) 
- socialshare-title="vm.goal.goalText"       //not working
- socialshare-url="{{share.goalURL}}"        //Only this is working

I'm not getting image, title etc.... Only  socialshare-url is working. Please help me how to share Image and title also. I'm attaching the screenshot how my fb page is looking after adding all these attributes.
![i284 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/16221924/29029925-f47b23c0-7ba6-11e7-8cfe-c53c9d243c8c.jpg)

I want sharing my page as following:
![image](https://user-images.githubusercontent.com/16221924/29030076-831e823e-7ba7-11e7-9ac7-494a8d60751f.png)
