### ISSUE TITLE
If an attribute does not have a default value, it is not tracked, and will keep an empty value even if updated

### ISSUE THREAD

**Issue by xelhark** [720kb/angular-socialshare#20]
I spent quite some time trying to understand why my dynamically loaded pinterest media image wasn't showing up in the pinterest share button. I ended up debugging and finding out that if the attribute is not set, the angular-socialshare directive just won't track it, so even if at another point in time you set that property, the plugin won't notice and won't use it.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-socialshare/releases/tag/0.1.8
Updated bower and tag thank you for the PR
