### ISSUE TITLE
Share multiple images on Facebook

### ISSUE THREAD

**Issue by ksshafik** [720kb/angular-socialshare#203]
How can I post multiple images to facebook in a single share

**Comment by 45kb** [comment]
@ksshafik I believe is not possible, have you had a look at facebook share documentation? If it's not there it is not possible.

**Comment by ksshafik** [comment]
@45kb I believe this feature is possible. Could you please check this: http://stackoverflow.com/questions/33506661/facebook-share-link-with-more-than-one-image

**Comment by 45kb** [comment]
@ksshafik that's open graph, so you can add images to the meta:og and leave blank the media option in socialshare.
