### ISSUE TITLE
How to share data:image/png;base64 with angular-socialshare

### ISSUE THREAD

**Issue by wearehappybits** [720kb/angular-socialshare#204]
It is not exactly an issue, but I am seeking for advice.

I am using plugins directive and what I want to do is to pass current state of canvas via facebook share:

              <a class="btn btn-medium center-content color-black radius3 bg-white"
                    socialshare
                    socialshare-provider="facebook"
                    socialshare-type="feed"
                    socialshare-via="145634995501895"
                    socialshare-to=""
                    socialshare-from=""
                    socialshare-ref=""
                    socialshare-display="popup"
                    socialshare-media= {{data }}
                    socialshare-source=""
                    socialshare-description="Yes it's super awesome, seriously!"
                    socialshare-text="720kb"
                    socialshare-caption="720kb is awesome"
                    socialshare-url="http://720kb.net"
                    socialshare-redirect-uri="https://developers.facebook.com/tools/explorer">
                    <span class="icon-facebook"></span> Facebook
                    </a>

Where we have {{ data }} it means that data:image/png;base64 comes in there, but of course it is not working. What should I do in order to make this work?

**Comment by 45kb** [comment]
@wearehappybits i don't think facebook allows base64 images, afaik you must provide a url for the image to be shared.

Maybe (not tried) you could try add `<meta og:image content="your base 64 image here"/>` and sharing the page url see if the image gets shared, but i guess not...

**Comment by 45kb** [comment]
Seems like facebook is now ignoring any picture other than OG:META image, see Facebook Open Graph Markup on how to customize photos and previews.

closing
