### ISSUE TITLE
Need to get Social sites Share or Post Response

### ISSUE THREAD

**Issue by vasu592** [720kb/angular-socialshare#206]
My requirement is Share or Post some Video URL's to Social media sites and need to increment a share count against that particular video in Database.
If I get the post response then I will increment in Database. Other wise what can I do for this requirement.
Note: I can not use your social media counts, why because I should increment a share value in Database.

**Comment by 45kb** [comment]
@vasu592 Hi, someone already asked this, there are no callbacks in angular-socialshare you should integrate the social SDK or API  https://github.com/720kb/angular-socialshare/issues/161
