### ISSUE TITLE
Facebook share stopped working?

### ISSUE THREAD

**Issue by tomanthoni** [720kb/angular-socialshare#207]
Can it be that the facebook share stopped working because of changes at Facebook? Title, description, media en caption parameters are being ignored and are being overridden by og parameter in the html of the target.

**Comment by 45kb** [comment]
@tomanthoni does it work if you remove the og metas completely?

**Comment by tomanthoni** [comment]
Sadly, this is not an option. They want that if you paste the url in the Facebook create post field that you also have a nice preview. And an extra: this preview has to be different than when you share it via the social-share plugin. So I thought I override this via the use of the parameters of the plugin...

**Comment by 45kb** [comment]
@tomanthoni yeah, that's what i suspected to be, simple sharing and you must provide a valid url for image sources so they can have preview in the share dialog, correct?

Otherwise you must use their SDK to upload new images i guess...

**Comment by 45kb** [comment]
@tomanthoni i don't quite understood actually 😆  could you please tell me what's going wrong and if anything we could do for this?

**Comment by tomanthoni** [comment]
I'm sorry, true, maybe I'm not so clear. :)

So:

1) when someone goes to Facebook.com, types the url of our campaign in the 'create post' field they want a nice link - preview. Meaning: I have to add og tags to the html.
2) when someone shares the url of our campaign on the website of our campaign I use the social-share plugin. They share the same url, but we want that the text in the Facebook link preview is different (so not the content inside the og tags.). So I use the parameters like 'socialshare-description'. But when I do this, I see the content of the og tags in the preview, and not the value I submitted via the 'socialshare-description' parameter.

I hope this is more clear?

**Comment by tomanthoni** [comment]
ps: I investigated a little bit and Facebook changed things.

Even do I use the Share dialog instead of the Feed dialog in the documentation of Facebook they state the following.

As of April 18, 2017, the following parameters are no longer supported by Graph API versions 2.9 and higher. For versions 2.8 and lower, the parameters will continue working until July 17, 2017.

https://developers.facebook.com/docs/sharing/reference/feed-dialog

**Comment by 45kb** [comment]
@tomanthoni you're right

Feed Dialog deprecated parameters:
![schermata 2017-06-16 alle 12 17 17](https://user-images.githubusercontent.com/7761650/27222759-dad735a4-528d-11e7-8b42-8e991ad79ed2.png)

This is what you mean?

**Comment by 45kb** [comment]
@tomanthoni updated the README and the lib i removed the deprecated parameters, thanks for spotting this out 👍

**Comment by tomanthoni** [comment]
No, thank you for your library! You removed it from the 'feed' social type, but I believe it also stopped working with the 'share' social type, because this is the one I was using...

**Comment by 45kb** [comment]
@tomanthoni are you sure? I compared the API doc parameters for each share type and reported them into the library... looks ok now... they aren't talking about share dialog deprecations...

**Comment by 45kb** [comment]
check here https://developers.facebook.com/docs/sharing/reference/share-dialog 

there is no deprecation for share dialog.

**Comment by tomanthoni** [comment]
I think so...
If I go to the feed dialog documentation:
https://developers.facebook.com/docs/sharing/reference/share-dialog

There is nothing about a 'description' parameter. Moreover, they state the following: 'Include open graph meta tags on the page at this URL to customize the story that is shared back to Facebook.'

So not possible to customize the story with the 'description' parameter, no?

**Comment by 45kb** [comment]
you're right, i think the problem is only that the README is wrong, i will double check it later

i believe share is used where it should be `sharer` which is different

**Comment by 45kb** [comment]
@tomanthoni ok i refactored the READMe facebook section base on what the new documentation states https://github.com/720kb/angular-socialshare/blob/master/Readme.md#facebook

Have a look, you was right, facebook now retrieve the images, captions and preview from the og:meta

thank you :)
