### ISSUE TITLE
Facebook share currently not working with angular-socialshare

### ISSUE THREAD

**Issue by Moses-Bassey** [720kb/angular-socialshare#209]
I just noticed on the website i integrated angular-social share that facebook share just stppped working, please is there any work around solution for this? 

![capture](https://user-images.githubusercontent.com/8930223/27237456-0e2de3b6-52c1-11e7-868b-7ba7f7bde679.PNG)

**Comment by 45kb** [comment]
@Moses-Bassey what version of angular-socialshare?

**Comment by Moses-Bassey** [comment]
I am using version 2.3.7

**Comment by 45kb** [comment]
@Moses-Bassey That looks more like a facebook temporary problem, however try to upgrade to `2.3.10` and let me know.

Also please paste here your html code for further help

**Comment by Moses-Bassey** [comment]
I have upgraded the library to v2.3.10.

Also here is the code snippe you requested

 <div class="btn btn-primary"
                                                                     socialshare
                                                                     socialshare-provider="facebook"
                                                                     socialshare-type="share"
                                                                     socialshare-description="mygtunes.com is a home of entertainment raging from Music to Movies, Life performances, TV Shows, Games and General talent."
                                                                     socialshare-via="11111110106654664111"
                                                                     socialshare-media="{{talentProperties.image}}"
                                                                     socialshare-quote="Uploaded by: {{talentProperties.userName}}"
                                                                     socialshare-hashtags="#myhashtags"
                                                                     socialshare-display="popup"
                                                                     socialshare-title="MY title"
                                                                     socialshare-caption="my caption"
                                                                     socialshare-url="www.website.com/{{talentProperties.id}}"
                                                                     socialshare-popup-height="400"
                                                                     socialshare-popup-width="400"
                                                                     socialshare-trigger="click">
                                                                    <i class="fa fa-facebook"></i> Facebook
                                                                </div>

**Comment by 45kb** [comment]
@Moses-Bassey follow the [README](https://github.com/720kb/angular-socialshare#facebook) things are changed, not all the attributes you are using are still available for facebook.

Also be sure your app_id is correct.

**Comment by Moses-Bassey** [comment]
Please can you help out with a work around solution for this, really need the image to show using data binding, i have home through  the documentation but am still facing similar issue.
