### ISSUE TITLE
Facebook share doesn't support all attributes

### ISSUE THREAD

**Issue by alejandroiglesias** [720kb/angular-socialshare#211]
Hi, I'm trying to replace the manually-baked Facebook sharing we use in our app with angular-socialshare. The only issue I find is that not all attributes are supported and that my sharing dialog now lacks title, description and image. I would like to compare my current solution vs my angular-socialshare implementation, and would like to add that I'm testing my local angular-socialshare implementation by using [ngrok](https://ngrok.com/) to access my local dev server from the Internet.

This is how it looks with our current solution vs after adding angular-socialshare:

![Current solution](https://user-images.githubusercontent.com/480640/27349004-4a5ed256-55cc-11e7-8eb0-3d4585f40e0c.jpg)![With angular-socialshare](https://user-images.githubusercontent.com/480640/27348987-38142b28-55cc-11e7-9f49-b492842580f4.jpg)

Besides how they look, the URLs are different, which is the reason why they look the way they do.

Currently:
```
https://www.facebook.com/dialog/feed?display=popup&link=http%3A%2F%2Fstory-local.<myserver>.com%3A4001%2F123eec2a-6a08-4c59-8d6c-27f397ad2121&app_id=<appid>&name=IRONMAN&description=During%20an%20awards%20banquet%20for%20the%20Waikiki%20Swim%20Club%2C%20John%20Collins%2C%20a%20Naval%20Officer%20stationed%20in%20Hawai%60i%2C%20and%20his%20wife%20Judy%2C%20began%20playing%20with%20the%20idea%20of%20combining%20the%20three%20toughest%20endurance%20races%20on%20the%20island%20into%20one%20race.%20They%20decided%20to%20issue%20a%20challenge%20to%20see%20who%20the%20toughest%20athletes%20were%3A%20swimmers%2C%20bikers%2C%20or%20runners.%20On%20February%2018%2C%201978%2C%2015%20competitors%2C%20including%20Collins%2C%20came%20to%20the%20shores%20of%20Waikiki%20to%20take%20on%20the%20first-ever%20IRONMAN%20challenge.&caption=story.<myserver>.com&picture=https%3A%2F%2Fs3.amazonaws.com%2Fgallery.<myserver>.com%2F123eec2a-6a08-4c59-8d6c-27f397ad2121.story.png
```

With angular-socialshare:
```
https://www.facebook.com/dialog/feed?&app_id=488652641275825&link=http%3A%2F%2Fee729c25.ngrok.io%2F123eec2a-6a08-4c59-8d6c-27f397ad2121&display=popup
```

Notice is the missing `name`, `description`, `caption` and `picture` query-string parameters. I wonder how to achieve that since those attributes are not supported by the directive? My end goal is to have the same URL (maybe the `caption` is not important, but `name`, `description` and `picture` are).
Thanks a lot in advance.

**Comment by 45kb** [comment]
@alejandroiglesias please look at #207 
Facebook is going to deprecate those attributes in favor of Open Graph Metas, just remove them

https://user-images.githubusercontent.com/7761650/27222759-dad735a4-528d-11e7-8b42-8e991ad79ed2.png

**Comment by alejandroiglesias** [comment]
Thank you very much and sorry for the dupe issue. It seems I made a very bad search before opening this one.
