### ISSUE TITLE
Sharing popup on Firefox 39 (Mac) doesn't scroll using trackpad

### ISSUE THREAD

**Issue by ishansharma** [720kb/angular-socialshare#24]
Noticed this when adding #23. 

Chrome and Safari display scroll bars and allow scrolling but Firefox doesn't have a scroll bar and trackpad doesn't work. Scrolling using arrow keys works fine though.

**Comment by 45kb** [comment]
@ishansharma i would close this, as it's own Browser problem i guess, since we are using a simple ```window.open``` and it's standard everywhere, am i wrong or missing something?

**Comment by ishansharma** [comment]
Actually, I can play around with this. Will try another version or OS. Then it will be a bit more clear.

**Comment by 45kb** [comment]
@ishansharma  thanks :) let know

**Comment by 45kb** [comment]
Going to close this since it's not a module releated problem, but third parties problem, thank you
