### ISSUE TITLE
Center the popup

### ISSUE THREAD

**Issue by NetanelBasal** [720kb/angular-socialshare#26]
If you can center the popup in the screen it will be great.

**Comment by 45kb** [comment]
@NetanelBasal  thank you for reporting, this looks possible we will try something asap, PRs are always appreciated :100:

**Comment by NetanelBasal** [comment]
There is a problem with the socialshare-text in facebook, its seems like what i insert there is not showing in the share pop up.

**Comment by 45kb** [comment]
@NetanelBasal  Facebook does not allow direct text or images, check the answer here https://github.com/720kb/angular-socialshare/issues/12

It's a facebook problem unfortunately

**Comment by NetanelBasal** [comment]
You have a pull request that fix this not?

**Comment by 45kb** [comment]
@NetanelBasal  Facebook problem should be fixed soon by https://github.com/720kb/angular-socialshare/pull/25 if you are referring to that problem, for the centering of the popup no PR is present at the moment

**Comment by NetanelBasal** [comment]
Yes i talked about the facebook problem. thanks.

**Comment by 45kb** [comment]
You're welcome :)

**Comment by 45kb** [comment]
@NetanelBasal  now it's possible to share media and content on fb, thanks to @TheWrongAlice  :+1: 

You can check Readme on how to use it https://github.com/720kb/angular-socialshare#sharing-type

**Comment by NetanelBasal** [comment]
Thanks a lot!!

**Comment by 45kb** [comment]
You're welcome but it's all thanks to @TheWrongAlice ;)

**Comment by jrbecart** [comment]
Is it possible to add this javascript function?

```javascript
 function PopupCenter(url, title, w, h) {
    // Fixes dual-screen position                         Most browsers      Firefox
    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

    width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
    height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var newWindow = window.open(url, title, 'scrollbars=yes, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    // Puts focus on the newWindow
    if (window.focus) {
        newWindow.focus();
    }
}
```

It's from there: http://stackoverflow.com/questions/4068373/center-a-popup-window-on-screen

**Comment by 45kb** [comment]
@jrbecart  Hi there is already a popup centering function, could be it is not working properly, will check this asap :+1:

**Comment by cheves505** [comment]
Hey @45kb , can you tell me what is the centering function?

**Comment by 45kb** [comment]
@cheves505  Hi,  each of these https://github.com/720kb/angular-socialshare/blob/master/lib/angular-socialshare.js#L487
