### ISSUE TITLE
Google Sharing shows {{meta}}

### ISSUE THREAD

**Issue by jamesbyrneiitd** [720kb/angular-socialshare#32]
My title and meta description is empty in View-Source although it's filled when viewed under "inspect element".

This disables google+ to show the title and description correctly including the picture. I simply get {{meta}} instead of showing what it should. 

My title and description looks like this:
    <title ng-bind="(title | makeCaps)"></title>
    <meta name="description" content="{{meta}}">

If I add a static page with title and description showing correctly, google+ sharing button works!! Could you help me out?

**Comment by 45kb** [comment]
@jamesbyrneiitd  Yes that is because Google crawler can't understand {{meta}} you need something like this  https://github.com/steeve/angular-seo (but there are tons of libraries to achieve what you want)

The second option is to add meta via server, like PHP, node.js etc ..
