### ISSUE TITLE
Share callbacks

### ISSUE THREAD

**Issue by jcirionotero** [720kb/angular-socialshare#34]
It is possible to have a callback, when share by twitter.

**Comment by 45kb** [comment]
Hi @jcirionotero , we should look for a bit and see if is possible to implement it, also not only for Twitter, it could be a great feature for all  the providers (where allowed)

@TheWrongAlice  what you think?

**Comment by jcirionotero** [comment]
Hi @45kb , and you think it possible to do, how much time?

**Comment by TheWrongAlice** [comment]
Yes this should be possible...

**Comment by TheWrongAlice** [comment]
@jcirionotero I checked out Twitter's documentation: https://dev.twitter.com/web/tweet-button/web-intent
There is no callback parameter...

**Comment by jcirionotero** [comment]
Hello @TheWrongAlice, you're right, so I wondered if it was possible to implement this.

**Comment by TheWrongAlice** [comment]
I tried experimenting a bit, but I can't find a way to do it without changing the contents of the popup (which would be impossible in this case since it's Twitter) :disappointed:

**Comment by jcirionotero** [comment]
AngularJs has a module for facebook: https://github.com/Ciul/angular-facebook. This module allows using Facebook.ui, share a content and subscribe to callback response. This flow not have Twitter.

**Comment by TheWrongAlice** [comment]
As far as I can tell, this module is not for sharing, but for user authentication

**Comment by jcirionotero** [comment]
@TheWrongAlice:  Also lets you share, I use it for both functions. And works perfectly.

**Comment by TheWrongAlice** [comment]
Can you show me how you use it to share? (This will help me reverse-engineer their solution)

**Comment by jcirionotero** [comment]
something like that:

Facebook.ui({
        method: 'feed',
        picture: 'url_picture',
        name: 'Any...',
        description: 'Lorem ....',
        caption: 'Use ...',
        link: 'url for when you clicked'
      }, function (response) {
        if (response) {
          // TODO something
        }
      })

**Comment by jcirionotero** [comment]
the "response" is a object: {post_id: 'sad6as8d7f6sd87f6ds7f'} or null

**Comment by TheWrongAlice** [comment]
Ok, I will investigate some more :smile:

**Comment by jcirionotero** [comment]
I waiting your feedback, if in anything I can help, not have problem, i have a little experience, thanks for your time.

**Comment by TheWrongAlice** [comment]
I have failed to reverse engineer their code... It seems to me that this popup "magic" is created by Facebook themselves and not by the angular provider.
I am not sure how to proceed.

**Comment by 45kb** [comment]
My guess is that callbacks as well as share count and other cool features, could be available only byintegrating API SDKs, which means a huge (but very cool) work :dancers:

**Comment by 45kb** [comment]
Going to close this issue but you can refer to https://github.com/720kb/angular-socialshare/issues/36 @jcirionotero  :+1:
