### ISSUE TITLE
Dynamic attribute value

### ISSUE THREAD

**Issue by sunocean-sand** [720kb/angular-socialshare#35]
How can I include a dynamic URL in the socialshare-url? For example, https://website.com/link={{event.id}}

**Comment by 45kb** [comment]
Hi actually depends on your code, but we did not included any watcher for dynamic data, try creating a jsfiddle or a plunkr with  your code so that we can help more.

Anyway i think we will add watchers/observers for the directive attributes, that way will be possible for sure. :+1:

**Comment by TheWrongAlice** [comment]
@45kb if you add watchers, please make them an opt-in feature... like you would have to specify `socialshare-watch="true"`

I would hate having unnecessary watchers in my app, as they contribute a lot to memory problems in Angular.

**Comment by 45kb** [comment]
Yes i think is the best way :+1:

**Comment by 45kb** [comment]
Actually looks like there is already a watcher for that, could you be so gentlee to paste your code @sunocean-sand , better if a jsfiddle or plunkr.

**Comment by 45kb** [comment]
Going to close this issue but i will help you later if you reply :+1:
