### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by evermax** [720kb/angular-socialshare#37]
Hi! Is it possible that you add your repository on npm?
I think it would be really useful for people like me that are using browserify and require.

**Comment by 45kb** [comment]
@evermax  Hi, yes sorry for that, i am going to publish it :+1:

**Comment by 45kb** [comment]
shipped https://www.npmjs.com/package/angular-socialshare :+1:

**Comment by evermax** [comment]
I wasn't expecting such a fast answer, thank you very much!
And thanks for this project, it is so useful!

**Comment by 45kb** [comment]
@evermax You're welcome and thanks for the catch we really forgot to do that :package:

**Comment by evermax** [comment]
I think you need to specify the main file in the package.json via a the `main` keyword though. Otherwise it is not picked up!

**Comment by 45kb** [comment]
@evermax  ops, should be fixed now, can you confirm?

**Comment by evermax** [comment]
I confirm, it works.
Thank you very much! :thumbsup:

**Comment by 45kb** [comment]
:+1:
