### ISSUE TITLE
Support setting description to Facebook share

### ISSUE THREAD

**Issue by thezuck** [720kb/angular-socialshare#38]
When posting to the feed dialog, Facebook supports the description parameter, see here: https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.4.
If not set, the description is taken from page scraping.

The plugin should support setting the description parameter, much like other parameters.  Proposed API change:
add socialshare-description="xxx" to directive

result: add &description=encodeURIComponent(xxx) to the URL when using feed type for facebook

**Comment by 45kb** [comment]
@thezuck  Hi could you please try this file  https://github.com/720kb/angular-socialshare/blob/master/src/js/angular-socialshare.js 

following the README here: https://github.com/720kb/angular-socialshare#facebook-dialog

You should be able to specify everything about fb dialog now, if it works we will release everything under a new version.

Let know, thank you for reporting! :+1:

**Comment by thezuck** [comment]
on it

**Comment by thezuck** [comment]
@45kb Hi Flippo, this is almost good, you forgot to add
'description': '',
to the propDefaults = definition, otherwise it doesn't find the property and doesn't track it
by the way, you should ignore this property if it is not set so facebook can scrape it from the page

**Comment by 45kb** [comment]
@thezuck  awesome, would you PR this fix so i will then release a new version of the module? :)

Let me know if you can or i'll do it myself, no problems.

**Comment by thezuck** [comment]
Tempted to contribute, but if you don't mind doing that change it would be great.  Promise to be more active in future changes :)

**Comment by 45kb** [comment]
@thezuck Hey no problems, i will try something for the evening or maybe tomorrow morning ;)

**Comment by 45kb** [comment]
@thezuck could you be so gentle to retry, the file is updated now!

**Comment by 45kb** [comment]
Should work with the latest release https://github.com/720kb/angular-socialshare/releases/tag/0.1.12

In case of any further problem/error please re-open the issue, thanks @thezuck

**Comment by thezuck** [comment]
works like a charm!  thank you very much!

**Comment by 45kb** [comment]
glad for that, thanks @thezuck !
