### ISSUE TITLE
Usage in local files or Adobe Cordova apps

### ISSUE THREAD

**Issue by dec** [720kb/angular-socialshare#39]
Hello,

First of all thanks very much for angular-socialshare. Try it in local files or in an Adobe Cordova compiled app I found the directive doesn't work like expected. I think this problem can be solved just by prepend the "http" or "https" protocol to the social sites URL's? Or may this implied something that I can't view?

Anyway thanks so much for your work.

**Comment by 45kb** [comment]
@dec  Hi, actually we didn't test so much on cordova, we will do something for that.

However do you get any error ?

Did you already installed inAppBrowser plugin for cordova, because, you know, window.open() will not work without it.

Thank you for reporting the issue.

**Comment by dec** [comment]
Hello,

Thanks for your quick reply. Yes; the error simply means that we can't navigate to an URL like "file://facebook.com/etc/etc".

I look a bit at the directive source code and found that the shared services URL's do not start with "http" nor "https", then in HTML local files (Apache Cordova apps HTML files are local files too) the approach do not work as expected.

I think a possible solution can be to prepend the "http" or "https" to the shared services URL's. My question is why this is not added from scratch, then I asked because maybe I miss something else that cause you don't prepend the HTTP protocol to the URL's.

If I can help in something just tell me. I say if I can add more information or something else.

Thanks again!

**Comment by 45kb** [comment]
@dec  You're right, i will introduce asap a PREFIX in case it's window.cordova.

**Comment by dec** [comment]
Hello,

Thanks for your reply. Probably I can't explain very well (my poor english strikes again!) but I think there is no need to detect the location protocol or something. The only need to do is to add the protocol for all shared services URL's.

In fact you do it for some URL, for example, here is a piece of the directive latest release source:

```javascript
var urlString = 'https://www.facebook.com/dialog/feed?display=popup' +
```
As you can see such URL incorporates the HTTP protocol and then probably works like expected in both remote or local files. However, in this other line of the source:

```javascript
var urlString = '//www.twitter.com/intent/tweet?';
```

We can see how the URL doesn't start with the HTTP protocol, but just the "//". Probably this is good when we open a window in a remote (served) HTML file, but doesn't work in local HTML files.

Then probably the only change we must to do is to write something like this:

```javascript
var urlString = 'http://www.twitter.com/intent/tweet?';
```

In all the URL's that start only with the "//". I am not sure if we can use directly the HTTPS protocol instead of HTTP, or if this can be deferred to some option or what. Probably the HTTPS is accepted by the shared services without problems.

**Comment by 45kb** [comment]
New release https://github.com/720kb/angular-socialshare/releases/tag/0.1.12

In case you still receiving errors please re-open the issue, thank you.

**Comment by dec** [comment]
Thanks! I think they works like expected since I made the change before and try it in both simple HTML local files and an Apache Cordova app, at least using the InAppBrowser plugin.

**Comment by 45kb** [comment]
@dec  awesome, you're welcome, let know if any further problem then :+1:
