### ISSUE TITLE
Prevent default for the directive event

### ISSUE THREAD

**Issue by dec** [720kb/angular-socialshare#40]
Hello,

Thanks again for angular-socialshare!

If we use a sample piece of code like the below one:

```html
<a href="#"
socialshare
socialshare-provider="facebook"
socialshare-text="720kb angular-socialshare"
socialshare-url="http://720kb.net">
Share me
</a>
```
... we can enter in some problem: the "a" link is follow after the shared service popup appear, and therefore our app URL changes to "#" and our app page appear white and empty.

I am not sure, but a possible solution can be to use the "event" "preventDefault" method of the directive event binded function. Then the below line of code:

```javascript
element.bind(properties.eventTrigger, function onEventTriggered() {
```

... can be changed by this other couple of lines:

```javascript
element.bind(properties.eventTrigger, function onEventTriggered(event) {
  event.preventDefault();
```
Doing that the shared service popup appear and our app page nor URL never changes.

Hope this can help in some manner!

**Comment by 45kb** [comment]
Have you tried ```href="javascript:void(0)"``` ? :)

**Comment by dec** [comment]
Yes; certainly it's a way to do that. Maybe it's the right way. However, I think if the "A" tag is linked with an AngularJS directive which is suposed to do something and not to follow the default link behaviour then the "preventDefault" can be useful. 

In other words, what we expect when a link like that are clicked? Follow the link? Nope. We expect the directive to do their job. Anyway maybe I am wrong or both solutions can work then no worry about and close this issue if you wanted. :)

**Comment by 45kb** [comment]
@dec  we will introduce  the preventDefault() anyway i think :+1:
