### ISSUE TITLE
Deploy as a WebJar as well?

### ISSUE THREAD

**Issue by lennartj** [720kb/angular-socialshare#41]
It would be a great help if angular-socialshare would be deployed as a WebJar so it can be accessible from within a Maven build cycle. If you go to the link below, the webjars team can assist in getting it into the release pipeline:

http://www.webjars.org/request

**Comment by 45kb** [comment]
Hi, thank you for the tip, i personally don't know much about webjars, let's ping @wouldgo  here, i think is better :+1:
