### ISSUE TITLE
Share in facebook and google+ don't work when I use return of a function, like: {{ getShareUrl() }}

### ISSUE THREAD

**Issue by willianribeiro** [720kb/angular-socialshare#43]
Hey guys, 
It isn't working when I use the return of a function like the code below. When I try Facebook It open the popup but doesn't share, and when I try Google+ It shares but without the link. When I put URL in hardcoded way instead of use a return of a function It works. Like:  `socialshare-url="http://someurl.com"`

(For Twitter and Linkedin It's working perfectly).

HTML
```
<button tooltip="Compartilhar no Google+" type="button" class="btn btn-default" 
    socialshare
    socialshare-provider="google+"
    socialshare-text="Vaga disponível"
    socialshare-url="{{ getShareUrl() }}">
    <i class="fa fa-google-plus-square no-margin"></i>
</button>

<button tooltip="Compartilhar no Facebook" type="button" class="btn btn-default" 
    socialshare
    socialshare-provider="facebook"
    socialshare-text="Vaga disponível"
    socialshare-url="{{ getShareUrl() }}">
    <i class="fa fa-facebook-square no-margin"></i>
</button>
```

JS
```
$scope.getShareUrl = function () {
    return window.location.href;
};
```

**Comment by 45kb** [comment]
Hi, you should not need {{}} try without

**Comment by willianribeiro** [comment]
Thank you for be so fast!

I have reproduced it on plunkr: http://plnkr.co/edit/F0LQkt5IYpn0aoL2SbPW?p=preview

**Comment by 45kb** [comment]
@willianribeiro  it works http://plnkr.co/edit/N0q1ce8XbHOeeLsTiBny?p=preview

Always be sure to use ```dist/``` files 

You're welcome :+1:
