### ISSUE TITLE
LinkedIn: problems when title has ampersand

### ISSUE THREAD

**Issue by pfms** [720kb/angular-socialshare#44]
The title gets cut on the first ampersand of the text.
Suggestion: encodeURIComponent(data.text) instead of encodeURI(data.text)

**Comment by hkristjan** [comment]
The same problem is for the number sign (#). If you want to share something that is hashtagged it strips the text that follows #. pmfs solution solves the problem.

**Comment by 45kb** [comment]
Hi all, may i ask you to try this file https://github.com/720kb/angular-socialshare/blob/master/src/js/angular-socialshare.js

I changed ```encodeURI(data.text)``` to ```encodeURIComponent(data.text)``` everywhere in the code.

Let me know so that we can release a new version.

Thanks

**Comment by hkristjan** [comment]
Hello. It works. Thanks for the fast response.

**Comment by 45kb** [comment]
Thank you for your quick feedback @hkristjan 

Now you can a new version of the module including this fix!

https://github.com/720kb/angular-socialshare/releases/tag/0.1.14
