### ISSUE TITLE
Facebook socialshare-url

### ISSUE THREAD

**Issue by mikepc** [720kb/angular-socialshare#47]
Hi there!

I'm specifying the socialshare-url in a function:

    <button 
    class="btn btn-default btn-medium center-content radius3 bg-white"
    socialshare
    socialshare-provider="facebook"
    socialshare-url="{{socialUrl()}}"
    socialshare-text="{{pad.name}}">
    <i class="fa fa-facebook"></i> Facebook
    </button>

And in the controller:

		$scope.socialUrl = function(){
			return $state.href('viewPad', { padId: $stateParams.padId }, {absolute: true});
		};

This code is working for all social providers except for facebook. The facebook button has the correct socialshare-url BUT when I click the link the url is wrong. It's the url of the page that the button was clicked from.

Any ideas?

**Comment by 45kb** [comment]
@mikepc  Hi, have you console.log the url?

Can you paste it here, thanks

**Comment by mikepc** [comment]
Odd enough when I deployed it to my remote, it's working. I think it has to do something with the localhost thing? No idea. But it's working now! Thank you!

**Comment by 45kb** [comment]
@mikepc Facebook is a big mistake when debugging, many times their url caching, for example, makes your tests awful.

Anyway glad if it works now :+1:
