### ISSUE TITLE
Links broken after use socialshare

### ISSUE THREAD

**Issue by MarlonEtiene** [720kb/angular-socialshare#48]
Hello,

I have a problem in pages with socialshare like this

```
<a href="#"
   socialshare
   socialshare-provider="facebook"
   socialshare-text="<%posts.title%>"
   socialshare-url="<%posts.url%>"
   class="btn btn-default facebook">
    <i class="fa fa-facebook"></i> Facebook →
</a>
```
This work nice, open the facebook popup to share the link but,

```
<h2><a href="<%posts.url%>"><%posts.title%></a></h2>
```
Links like that stop to work, when I click the URI change, but the page not refresh.
Could you help please?

**Comment by 45kb** [comment]
Hi @MarlonEtiene  this looks really not a problem with socialshare module, because the module does not interest elements if they have not the socialshare attribute specified.

However, if you post a jsfiddle or plunkr link we may help you on this.

Thank you.

**Comment by MarlonEtiene** [comment]
Hello,
After some research I discovered when I configure $locationProvider to html5Mode I need to put target="_self" on my links.
After this update all links back to work.

Thanks!

**Comment by 45kb** [comment]
Hi @MarlonEtiene  does your links works if you remove socialshare module at all?

**Comment by MarlonEtiene** [comment]
Yes, If I remove socialshare links back to work.
But how I said, the "target" property solved my problem

Thanks!
