### ISSUE TITLE
The social facebook using feed type doesn't close the popup window

### ISSUE THREAD

**Issue by sjorquera** [720kb/angular-socialshare#50]
Hi!

I´m using the facebook share option and it´s impossible for me to close the pop up that is opened. Exist  some fix for this issue?

**Comment by 45kb** [comment]
Hi, have you tried ```socialshare-redirect-uri="https://developers.facebook.com/tools/explorer">``` ? should work using window.close() inside the page you redirect to.

**Comment by stijn26** [comment]
@45kb this doesn't work, the url inside redirect-uri must be a facebook url. For example when i put http://google.com as redirect-uri then the popup windows gives an error.

**Comment by 45kb** [comment]
Hi, yes unfortunately it's a facebook own property so atm i don't know how to solve and if it's possible to solve it, if you have any idea please share it!

**Comment by 45kb** [comment]
Actually not really possible, going to close the issue.

If any idea/trouble please re-open it.

Thank you.
