### ISSUE TITLE
Facebook "text" does not seem to be working anymore

### ISSUE THREAD

**Issue by DonHaron** [720kb/angular-socialshare#52]
When providing a text when sharing with Facebook, that text is ignored. As far as the Facebook Developers documentation goes, there is no mention anywhere anymore of providing a text for a share button. I believe this functionality is deprecated. Maybe the code and documentation could be updated to reflect that change. I can also make a pull request for this, if desired.

**Comment by 45kb** [comment]
Will look at this later, thank you @DonHaron  for the catch

**Comment by 45kb** [comment]
Ok facebook is not allowing text on sharer url , try using the dialog by `socialshare-type="feed"` this will let you set all these options you see here: https://github.com/720kb/angular-socialshare#facebook
