### ISSUE TITLE
If my url has a hashtag(#), the share url only has the part before the #...

### ISSUE THREAD

**Issue by hughred22** [720kb/angular-socialshare#53]
I cannot get the socialshare-url and socialshare-media working right. Here are my code: 

<md-button class="md-cyan-theme md-primary" href socialshare
                        socialshare-provider="facebook"
                        socialshare-url="{{metadata.url}}"
                        socialshare-media="{{video.data.videoThumbnail}}" aria-label="">
                            <md-icon md-font-icon="fa fa-facebook-square"></md-icon>
                            <span class="AR-mainvideo-innerbtntext">Facebook</span>
                        </md-button>

the metadata.url are in $rootscope, and the {{video.data.videoThumbnail}} return the image path. When I click the button, it only show the http://localhost:3000/ on the facebook popup, which the full url is http://localhost:3000/#/actor/matthew-del-negro

Also the image did not get render, just white with url http://localhost:3000/ in a input box...

**Comment by 45kb** [comment]
@hughred22 Hi, you should try without {{ }}

**Comment by hughred22** [comment]
without the {{ }}, the share URL will just show metadata.url instead of the actual value :(

**Comment by 45kb** [comment]
Hi, could you please put your code in here http://plnkr.co/edit/jiXiItN4GgXXqzULfN23?p=preview

So that i can check what's going wrong.

**Comment by hughred22** [comment]
I don't know how to use plnkr...
http://plnkr.co/edit/lJp3dDIherVItLHIaifD?p=preview

But I just want to put a value in $rootScope.metadata.url = "http://localhost:3000/#/actor/matthew-del-negro"; and then just display it on facebook share in socialshare-url="metadata.url"

**Comment by 45kb** [comment]
Try like this
http://plnkr.co/edit/0zZjHiGjbpVGhruBEFNz?p=preview

**Comment by hughred22** [comment]
It share the plnkr url, not the URL value passed in. 

<img width="1317" alt="screen shot 2015-11-11 at 12 12 00 pm" src="https://cloud.githubusercontent.com/assets/2126155/11101749/884cc90c-886d-11e5-936e-4c69c22a1114.png">

**Comment by 45kb** [comment]
Sorry yes i did not figure it out, actually looks like sharer won't get your url https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2F%23%2Factor%2Fmatthew-del-negro at all very strange i am making some tests right now 


If you want you can join me here https://gitter.im/720kb/angular-datepicker

**Comment by 45kb** [comment]
So from my tests looks like is a facebook problem that won't let share links like localhost if you try with a real domain it works, i am sorry for this, but we can't do much if they do not allow this
