### ISSUE TITLE
not working properly on iOS when combined with ng-touch

### ISSUE THREAD

**Issue by BerendWeij** [720kb/angular-socialshare#54]
I am having problems working with this library in combination with ng-touch. Most of the time, clicking on a social-share link will not work on iOS. Nothing happens. When I disable ng-touch, the social-share links are working.

**Comment by 45kb** [comment]
Hi @BerendWeij  yes you should try https://github.com/720kb/angular-socialshare#sharing-event-trigger

```socialshare-trigger="touchstart">```

Please re-open the issue if it doesn't fix

**Comment by BerendWeij** [comment]
Great! Works like a charm. Thanks for the quick response.

**Comment by 45kb** [comment]
You're welcome, glad that it works :+1:
