### ISSUE TITLE
Evernote

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-socialshare#56]
Please help us, if you know the correct sharer url for Evernote.com could be great to implement that.

Looks like: http://www.evernote.com/clip.action?url=[post-url]&title=[post-title]
doesn't work.

Thank you.

**Comment by Tketa** [comment]
www.evernote.com/clip.action?url=http://www.google.com&title=Google works for me!

**Comment by 45kb** [comment]
@Tketa  thanks a lot will give it a try! :+1:

**Comment by 45kb** [comment]
Released with https://github.com/720kb/angular-socialshare/releases/tag/0.2.3-beta
