### ISSUE TITLE
New problems when using social-share on device

### ISSUE THREAD

**Issue by paulschullian** [720kb/angular-socialshare#57]
Hello 720kb. I used your plug-in for social sharing & it worked just fine. Thank you by the way ! :)
Unfortunately, since a couple of days it doesn't work any more, but solely on my device, where it used to work just fine. When simulating the application wit ionic serve it works.
Thanks again :)

**Comment by 45kb** [comment]
Hi @paulschullian , could you please show some code and define better "It doesn't work" because there have been problems testing on localhost in the last days, Facebook looks like is no more allowing localhost sharing...

Thank you

**Comment by wouldgo** [comment]
Hi,
could be related to the fact that opening a new window is  different in ionic env (it should use the external plugin)?

**Comment by paulschullian** [comment]
![720kb](https://cloud.githubusercontent.com/assets/14993015/11180010/bc9f82f6-8c57-11e5-9ce0-70ac44563e59.png)
I included the tag in index.html and '720kb.socialshare' to the module.

Yes Sir, thank you.
A couple of weeks ago I followed your tutorial step by step & it worked just fine. There were no problems whatsoever, it worked perfectly on my android-device. Unfortunately a couple of days ago, when I submitted my last build to my boss he discovered that the icons don't trigger the functionality. I didn't mess with the file you see right now nor any other involving modules, tags, files or plug-ins. 
Kind regards.

**Comment by 45kb** [comment]
@paulschullian Ok, i am going to test on a blank new ionic app, are you sure you installed inAppBrowser plugin yes?

**Comment by paulschullian** [comment]
Yes Sir. Thank you very much.

**Comment by 45kb** [comment]
@paulschullian Hi, first of all use the minified file because the `src/` directory could not be updated or broken, then be sure to install the latest version of the module `bower install angularjs-socialshare`

I am going to test on the device, thanks.

**Comment by paulschullian** [comment]
Thanks @45kb. Will do :) Nice work you are doing here !

**Comment by 45kb** [comment]
Ok, can you try adding:  `  <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">` in your index.html?

Looks like without it doesn't work.

**Comment by paulschullian** [comment]
Hi. Unfortunately it doesn't solve the problem.
The situation is still that it works when simulating ->ionic serve.
But on the device it doesn't trigger anything.

Thanks for trying :) Much appreciated

**Comment by paulschullian** [comment]
![social](https://cloud.githubusercontent.com/assets/14993015/11183175/9ebe3b24-8c70-11e5-830a-ff04a9557a16.png)

Hi @45kb . Thanks for trying to help. It still works with ionic serve but not on the real device.
Is there a recent cordova-update corrupted?

**Comment by 45kb** [comment]
Well in that list i don't see cordova-plugin-inappbrowser

use this `ionic plugin add cordova-plugin-inappbrowser`

Also i don't know what the `cordova-plugin-x-socialsharing` stands for, are you sure it is needed?

Let me know if now it works please, thank you.

**Comment by paulschullian** [comment]
Thanks @45kb, works perfectly. I didn't have to uninstall cordova-plugin-x-socialsharing. I just used that first, before I found yours :D which I like way better. Thanks again for your help :)

**Comment by 45kb** [comment]
Ok, glad, you're welcome.
