### ISSUE TITLE
facebook provider url strips trailing path

### ISSUE THREAD

**Issue by treaz** [720kb/angular-socialshare#58]
Take the facebook example in the readme.md:
```
<a href="#"
socialshare
socialshare-provider="facebook"
socialshare-text="720kb angular-socialshare"
socialshare-url="http://720kb.net">
Share me
</a>
```

If you change the url to
```socialshare-url="http://720kb.net/something"``` it will fail to work.
This happens because the default (share.php) is deprecated. Maybe an update to the documentation would be necessary? I already lost around an hour on this. Hopefully, other people won't lose more time

**Comment by 45kb** [comment]
Hi @treaz  thank you for reporting this, do you have any source to check / read about the changes?

Thanks, much appreciated, i will look forward to make the changes for facebook :+1:

**Comment by treaz** [comment]
Actually, I've decided to drop the facebook button. I'm closing the issue
