### ISSUE TITLE
Twitter media share

### ISSUE THREAD

**Issue by asaryasv** [720kb/angular-socialshare#59]
Hi,

 I tried to share an image in twitter like this
<a  socialshare=""
    socialshare-provider="twitter"
    socialshare-text='test'
    socialshare-media="http://test.marketstreat.com/files/55e5a40864ad545666759d3a"
    socialshare-url="http://test.marketstreat.com">twitter
</a>
but it is not sharing the image ,

Thanks & Regards
ARYA S A

**Comment by 45kb** [comment]
Hi @asaryasv sorry it's a typo in the readme, looks like Twitter does not allow media sharing by sharer check here https://dev.twitter.com/web/tweet-button

**Comment by asaryasv** [comment]
Thanks for the immediate response

**Comment by 45kb** [comment]
you're welcome @asaryasv
