### ISSUE TITLE
Facebook socialshare-text not used

### ISSUE THREAD

**Issue by cdupoiron** [720kb/angular-socialshare#6]
Hi,

First, thank you for your work !

There is a problem when sharing on facebook, socialshare-text is not used. 
It works on twitter and linkedin with the same parameters.

Could you provide one example with socialshare-text used on facebook link please?

**Comment by 45kb** [comment]
Hi, it seems that facebook does not allow any param other than [url] so just share via socialshare-url=""

You find examples here: https://github.com/720kb/angular-datepicker/issues/11

**Comment by 45kb** [comment]
NOW it is possible https://github.com/720kb/angular-socialshare#sharing-type

**Comment by cdupoiron** [comment]
Thx, I'll test it soon :)

**Comment by 45kb** [comment]
Yes let know if any problem please, thanks :)

**Comment by clough1** [comment]
Hi @45kb,

Does FB still allow sending text? The #sharing-type URL provided does not take me to a Sharing Type section.

 Thank you.
