### ISSUE TITLE
Callback after Facebook share

### ISSUE THREAD

**Issue by alexislg2** [720kb/angular-socialshare#60]
Hey,
How can I have a callback triggered when someone shares on facebook?
Thanks

**Comment by 45kb** [comment]
Hi, specifying `socialshare-type="feed"`  you should be able to use facebook in "dialog" mode https://github.com/720kb/angular-socialshare#facebook

For further informations have al ook at their documentation:  https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.4

Probably redirect_uri is what you are looking for.

Actually there is no way to setup callbacks without using providers SDKs.
