### ISSUE TITLE
Facebook sharing ignores attributes other than socialshare-url

### ISSUE THREAD

**Issue by jakub94** [720kb/angular-socialshare#61]
I have a problem using the facebook sharing functionality. As the title says already I cannot specify any attributes using "facebook" as the socialshare-provider. I want to change the text but it is just ignored. the only thing working is the socialshare-url.
Even when I just copy the example from the documentation:

socialshare
socialshare-provider="facebook"
socialshare-text="720kb angular-socialshare" 
socialshare-url="http://720kb.net">
Share me

With twitter though it works just fine and without any problems.

Has anybody an idea and can help me with this? It would be greatly appreciated, thank you!

**Comment by 45kb** [comment]
Try using socialshare-type="feed" it's in the doc :+1: 
https://github.com/720kb/angular-socialshare/issues/52

**Comment by jakub94** [comment]
Thanks for your fast reply. I should have found this old post, my bad.
Unfortunately though using socialshare-type="feed" results in facebook saying: "An error occurred. Please try again later." on the facebook website.

**Comment by 45kb** [comment]
Yes, check the readm for all the "dialog" options, you will probably need to pass the app_id and so on to the dialog.
