### ISSUE TITLE
Is it possible to pass a $scope variable inside this directive socialshare-url ?

### ISSUE THREAD

**Issue by sakram80** [720kb/angular-socialshare#63]
Hi all,
I am trying to pass a scope variable but it is going back to default, somehow it is not recongizing it. Would be really great if someone can help
best regards,

**Comment by 45kb** [comment]
Hi @sakram80  for sure it is possible, paste your code or make a jsfiddle/plnkr so that we can help you.

**Comment by sakram80** [comment]
Hi 45kb,

Thanks for your reply. Here is plunker. Idea is very simple I am trying to share a location which is defined inside controller scope. Here is plunker:
http://plnkr.co/edit/Ups9sqynbTi62LeUqqZ6?p=preview

best regards,

**Comment by 45kb** [comment]
Hi @sakram80 , thank you for the fiddle, i was building one for you in the meantime, check here http://plnkr.co/edit/9wHgkeoEc2ILfr9zVT6D?p=preview

You can see `socialshare-url="{{url}}"`

**Comment by sakram80** [comment]
Thanks man

**Comment by 45kb** [comment]
You're welcome :+1:
