### ISSUE TITLE
The share text on Facebook and Google + does not work

### ISSUE THREAD

**Issue by ignacio-chiazzo** [720kb/angular-socialshare#68]
Awesome tools! However I can not share a text on google +. Why not?

If you change this code 

<div class="col6 offset-left2">
    <div>
      <button class="btn btn-medium font-bold"
      socialshare
      socialshare-provider="facebook"
      socialshare-type="sharer"
      socialshare-text="720kb"
      socialshare-url="http://720kb.net"
      socialshare-popup-height="300"
      socialshare-popup-width="400"
      socialshare-trigger="click" >
      <i class="fa fa-facebook"></i> Share on Facebook (sharer)
    </button>
  </div>

to 

<div class="col6 offset-left2">
    <div>
      <button class="btn btn-medium font-bold"
      socialshare
      socialshare-provider="facebook"
      socialshare-type="sharer"
      socialshare-text="new text"
      socialshare-url="http://720kb.net"
      socialshare-popup-height="300"
      socialshare-popup-width="400"
      socialshare-trigger="click" >
      <i class="fa fa-facebook"></i> Share on Facebook (sharer)
    </button>
  </div>

This does not work, the text is always showing 720kb

**Comment by 45kb** [comment]
Hi @ignacio-chiazzo Both Facebook and Google + does not allow text, they retrieve all the infromations directly from the url you share.

About Facebook you can use `socialshare-type="feed"` see the documentation for "dialog" attributes then https://github.com/720kb/angular-socialshare#facebook
