### ISSUE TITLE
Google+ url sharer text ?

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-socialshare#71]
Any idea?

**Comment by mebibou** [comment]
Looking at the documentation, there is no other option than url and language : https://developers.google.com/+/web/share/#quick-look

It will automatically pick up the title and description from the meta-tags of the shared page, nothing to do here

**Comment by 45kb** [comment]
Thanks @mebibou thanks to confirm 👍  , let's see if they will change anything in the near future, i hope!
