### ISSUE TITLE
I found a bug in the facebook feed

### ISSUE THREAD

**Issue by archasek** [720kb/angular-socialshare#72]
In the line 404 of unminified module.

Instead of:
        `var urlString = 'https://www.facebook.com/dialog/feed?display=popup&app_id=' + encodeURI(attrs.socialshareVia) + '&redirect_uri=' + encodeURI(attrs.redirectUri);`

it should be:

`        var urlString = 'https://www.facebook.com/dialog/feed?display=popup&app_id=' + encodeURI(attrs.socialshareVia) + '&redirect_uri=' + encodeURI(attrs.socialshareRedirectUri);
`

Hope that will help anybody ;)

**Comment by 45kb** [comment]
Thank you @archasek  , you can try with the new version https://github.com/720kb/angular-socialshare/releases/tag/0.2.2-beta

I just changed what you highlighted.

**Comment by archasek** [comment]
@45kb I think there should be an option not to add `redirect-uri` at all. Now it adds `&redirect-uri=undefined` to the url. I think it should not be added then. What do you think?

**Comment by 45kb** [comment]
@archasek  Thank you, if you encounter some other problem feel free to report them!

Have a nice day.
