### ISSUE TITLE
share image

### ISSUE THREAD

**Issue by deryfebriantara** [720kb/angular-socialshare#78]
is this directive can share some image? and is this posible to implement on hybird mobile app?

**Comment by 45kb** [comment]
Hi @deryfebriantara 

For images, it all depends on the social provider and their API rules, some allow images and media some other not. Check in the doc which option is available for each provider https://github.com/720kb/angular-socialshare#doc

This module works on hybrid apps, if you mean webview embed javascript apps, like cordova/ionic apps.

**Comment by deryfebriantara** [comment]
yes i will implement on ionic framework.. thank you for the explanation.
