### ISSUE TITLE
data binding for facebook feed share

### ISSUE THREAD

**Issue by florisca** [720kb/angular-socialshare#79]
There is the following issue:
I have dynamically changing url (photo gallery) and trying to share the image. The $scope.image for socialshare-attributes is created when the share button is clicked (via ng-click). In the facebook share window the binding will not be created until the second attempt.

Steps:
1. Open a url with socialshare button on it
2. Create a controller which creates a scope: $scope.click = function() { $scope.image = 'image name'}
3. Add the ng-click to html: <button type="submit" ng-click="click()" ...socialshare-text={{image}}, etc...> the button {{image}}</button>
4. Yes, {{image}} is added in both places, button attribute value, for socialshare-text, and button text
5. click the button (the button text will be binded to {{image}}, the facebook share won't be binded
6. Close the facebook window and click the button again
7. The socialshare-text is now binded

**Comment by 45kb** [comment]
@florisca Hi, first i have to admit i don't quite understand the steps, more specifically the last 4 steps, this is actually a problem for me, i would help you.

Could you try to make a fiddle or plnkr? That could be very helpful

Thanks

**Comment by florisca** [comment]
Yes, sorry for the poor post description, please see the fiddle here. You can see that the $scope is updated in the html, at the button tag, but not at the fb social share window.
http://jsfiddle.net/florisca/v6uw9sdu/1/

**Comment by 45kb** [comment]
Is this what you need? http://jsfiddle.net/v6uw9sdu/7/

I just added `ng-mousedown=""` instead of `ng-click=""` which gets fired before the click i suppose.

**Comment by florisca** [comment]
Unfortunately, the facebook share window is empty in your last fiddle...I attached an image of what I see.
![screen shot 2016-02-17 at 10 12 38](https://cloud.githubusercontent.com/assets/9482811/13103492/7c898792-d55f-11e5-93f9-f0bc60519342.png)

**Comment by 45kb** [comment]
Yes sorry, that's due the fact the url is empty for facebook, check with google http://jsfiddle.net/v6uw9sdu/8/

**Comment by florisca** [comment]
Yes, genius, the issue is solved. Still, it shouldn't have caused the trouble with ng-click either. Thank you for the solution, this is not really a bug then, it will be closed.

**Comment by 45kb** [comment]
You're welcome, then we are looking forward to implement a better way to handle events, to call socialshare also from controller could be great for example.

Have a nice day.
