### ISSUE TITLE
Facebook 'feed' share no longer working

### ISSUE THREAD

**Issue by RichardLanders** [720kb/angular-socialshare#80]
As the title suggests, when setting the socialshare-type to 'feed' this is the error I get from facebook: 'An error occurred. Please try later', was definitely working yesterday however.

**Comment by 45kb** [comment]
Hi, please @RichardLanders paste how you using it.

Some fiddle or plnkr could be great to help you.

That error is usually a facebook error, not a module error.

**Comment by RichardLanders** [comment]
Humble apologies, I realised that I hadn't set my "socialshare-via". Not to sure why it was working a few days ago but adding my app id to "socialshare-via" has sorted out the problem.

Thanks @45kb

**Comment by 45kb** [comment]
Of course app_id is a mandatory param for facebook, you're welcome, glad that you fixed!
