### ISSUE TITLE
FB dialog doesn't work on some computers

### ISSUE THREAD

**Issue by archasek** [720kb/angular-socialshare#82]
Hi. We recognized that on some computers dialog doesn't work and FB responses with an error.
To fix that I had to add these parameteres to our urlString.

&origin
&relation
&frame
&result
(not sue if all of above are mandatory or only some of them).

**Comment by 45kb** [comment]
@archasek Hi, thanks for reporting it, may i ask you wich computers and browsers are involved?

What's the error message from facebook?

**Comment by archasek** [comment]
![image](https://cloud.githubusercontent.com/assets/2247211/13321471/792fba00-dbcf-11e5-8f08-e00dee8a2909.png)

Note that I didn't add any redirect-uri parameter at all. This error occurred only on some PCs. Chrome/FF. I have no idea what was wrong.

**Comment by 45kb** [comment]
Actually, i am not 100% sure if redirect-uri is required by facebook, could you please paste the url that is inside the popup address bar, thanks.

**Comment by archasek** [comment]
Can you give me your email address?

**Comment by 45kb** [comment]
If you need to chat with us you can join here whenever you want https://gitter.im/720kb/angular-socialshare

My email is filippo~at~720kb.net

**Comment by 45kb** [comment]
Closing, if you still having problems, let know, thanks.
