### ISSUE TITLE
FB dialog isn't closed after share

### ISSUE THREAD

**Issue by archasek** [720kb/angular-socialshare#83]
It's stil visible, but empty inside. How can I handle it?

**Comment by 45kb** [comment]
@archasek  that's probably because you don't specify any redirect-uri which could close the popup if you want.

**Comment by archasek** [comment]
Are you sure? As I tested it some time ago, it wasn't closing the popup, but it just was redirecting to the redirect-uri INSIDE the popup. Can you check it?

**Comment by 45kb** [comment]
@archasek there is no way to close the popup using the module, popup closing it's up to providers.

**Comment by 45kb** [comment]
Closing issue, if you still having problems let know, thanks.
