### ISSUE TITLE
Cant seem to configure facebook text

### ISSUE THREAD

**Issue by adenta** [720kb/angular-socialshare#84]
Hi!

right now my code looks like: 
`    <a class=" right btn-floating red" socialshare
socialshare-provider="facebook"
socialshare-text="foo"
socialshare-description="bar"
socialshare-url="{{link.url}}" style="right:24px;">
      <i class="large material-icons">web</i>
    </a>`

I can't seem to get facebook to fill in the text I am trying to pass? I would like it if 'foo' was automatically entered into the sharing dialog on facebook. Where do I need to troubleshoot?

**Comment by 45kb** [comment]
Hi @adenta that's due the fact that facebook does not accept text when using "sharer" method.

You have 2 options:
1 - set a `<meta og:description="bar"/>` tag for you page
2 -  look at the "dialog" method here https://github.com/720kb/angular-socialshare#facebook

The only way to share text on facebook is to use the dialog mode or open graph meta tags, the official dialog documentation is here: https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.4
