### ISSUE TITLE
When facebook share dialog comes up, it shows share_platform_default as the share with name

### ISSUE THREAD

**Issue by santhotech** [720kb/angular-socialshare#85]
![capture](https://cloud.githubusercontent.com/assets/475261/13515776/4eb79ed8-e182-11e5-81af-784166e20ca8.JPG)

If a user is not logged in when they click the share button, the facebook login dialog comes up. It says 
"Log into share with share_platform_default" instead of the application name.

**Comment by 45kb** [comment]
@santhotech Hi, thanks for reporting this.

Are you using `socialshare-type="feed"` ?
If yes, are you setting up `socialshare-via=""`  (which means you share using an application).

If you can please paste here your html so that i cant make tests.

Thanks :+1:

**Comment by 45kb** [comment]
Closing, if you still having problems, let know. Thanks
