### ISSUE TITLE
Google+ and LinkedIn is not working

### ISSUE THREAD

**Issue by louisgv** [720kb/angular-socialshare#97]
The G+ on the demo page is not working for me: http://720kb.github.io/angular-socialshare/

And Specifically LinkedIn is not working for me in my project. Here's my code:

```
<button class="btn btn-primary social-linkedin" socialshare socialshare-provider="linkedin" socialshare-text="Checkout my awesome Site!" socialshare-description="My Awesome Site" socialshare-url="{{baseUrl + swurvey.id}}">
                    <i class="fa fa-linkedin"></i>
                    <!-- LinkedIn -->
                  </button>

                  <button class="btn btn-danger social-google" socialshare socialshare-provider="google+" socialshare-url="{{baseUrl + swurvey.id}}">
                    <i class="fa fa-google-plus"></i>
                    <!-- Google+ -->
                  </button>
```

**Comment by 45kb** [comment]
Hi @louisgv yes google+ stopped working i will check this, as for linkedin it works normally here, which browser are you using and please check if you have the latest version of the module.

**Comment by psychowood** [comment]
Is it a problem of the demo page alone? My project (code pulled yesterday with bower install) is still working for both.

**Comment by 45kb** [comment]
It is a problem with google provider naming, looks like it is fixed with https://github.com/720kb/angular-socialshare/releases/tag/0.2.6-beta

You just have to call socialshare-provider="google" and not google+

**Comment by psychowood** [comment]
Just noticed bower pulled v0.1.X for me... my bad :)

**Comment by 45kb** [comment]
Yes, there are prereleases i am releasing the final 2.0.0 will be available in a while :+1:

**Comment by 45kb** [comment]
Ok with `2.0.0`  this problem looks fixed! Thanks for reporting :100:
